artifact :bloom_relics do
  name "Bloom Relics"
  path "player/artifacts/relics/bloom-relics.md"
  reviewed "2026-03-19"
  tags :resonance, :danger
  prominence :recognized

  prose <<~PROSE, section: :significance, heading: "Significance"
    Pre-Glassfall artifacts of exceptional power are individually unique and don't constitute a "resource" in the trade sense — they are found, not manufactured. But they circulate through the system's economy as objects of extreme value, and a few categories deserve mention.

    **Intact ringglass** is covered in the #{ref :ringglass, "ringglass entry"} — ring-era crystal with configurations nobody can replicate.

    **#{future "Bloom Zone"} relics** are something different. These are artifacts generated by the reality distortion in active Bloom Zones — not pre-Glassfall, but genuinely new. The distortion produces objects with properties that have no precedent: materials with impossible geometry, crystals that resonate at narrow bandwidths without being tuned, devices of unknown function that demonstrably work. These are not well understood, and the #{ref :displacement_council, "Displacement Council"} officially discourages removing them from containment zones. The removal happens anyway, funneled through black market channels and smuggling networks.

    **Named relics** exist — unique artifacts with individual reputations. A tome said to grant good fortune to its readers. A spear forged in dimensions that shouldn't coexist, capable of piercing any known material and extremely difficult to store safely. These circulate through legend, private collections, and occasionally the black market. Each one is a story.
  PROSE
end

relate :rel_bloom_relics_manifests_at_bloom_zones, :manifests_at, :bloom_relics, :bloom_zones do
  prose "Bloom relics come out of the #{ref :bloom_zones, "Bloom Zones"} — artifacts the distorted reality there produces and nobody fully understands."
end
relate :rel_bloom_relics_derived_from_resonance, :derived_from, :bloom_relics, :resonance do
  prose "They register as #{ref :resonance, "resonance"} artifacts of relic magnitude, behaving in ways standard ringglass theory says they shouldn't."
end
