concept :resonance do
  name "Resonance"
  subkind :physical_system
  path "player/cosmology/resonance.md"
  status :complete
  reviewed "2026-06-18"
  tags :resonance
  prominence :mythic
  registry true
  function "Carries power, motion and information through tuned materials"
  nature "Ambient energy present throughout the Kaleidos system"
  known_forms "Structural, kinetic and signal bands"
  operating_limit "Local fields deplete and effects fade away from ringglass"

  prose <<~PROSE
    Resonance is a fundamental property of the Kaleidos system — a low-level energy that permeates the local environment the way background radiation permeates a star system. It's present on every body in the system: the surface of Kaleidos, the moons, the #{ref :the_glass_frontier, "ring habs"}, even the outer planetary bodies, though at varying intensities. It isn't generated by any single material or structure. It simply is.

    What the original builders discovered was that a crystalline material — now called #{ref :ringglass, "ringglass"} — resonates with this ambient energy in stable, predictable ways. Ringglass doesn't create resonance. It concentrates and channels it, the way a lens focuses light that was already there. The builders used this property to move power, data, and physical force through the ring structure without cables or broadcast towers. Tune a section of ringglass to the right frequency, and it would pass energy along to the next section, and the next, like a vibration traveling down a wire.

    When the rings #{ref :the_glassfall, "shattered"}, the ringglass scattered — across the surface of Kaleidos, into orbit, into the soil and water — and it kept resonating. Not in the organized, purposeful way the builders intended, but in a diffuse, amplified hum. The ambient resonance that was always present became far more noticeable, because now there were trillions of crystal fragments concentrating it from every hillside and riverbed. After #{elapsed :the_glassfall, approx: true} of settling debris, ringglass is almost everywhere on Kaleidos — and with it, resonance strong enough to use.

    Resonance is not magic. It's not the residual output of a broken machine. It's a natural energy that the builders learned to harness, and that the people of the system are slowly relearning how to use — with cruder tools and less understanding than the #{ref :elves, "elves"} ever needed.
  PROSE
  prose <<~PROSE, section: :how_it_works, heading: "How It Works"
    Resonance operates across two dimensions: **band** (what kind of effect) and **bandwidth** (how focused the application).

    ### The Three Known Bands

    Ringglass vibrates across a spectrum. The builders encoded specific physical effects into specific frequency ranges:

    **Structural** — reinforces physical bonds. Makes materials harder, denser, more resilient. Ringglass-reinforced concrete is standard construction on Kaleidos. The most common practical application and the one with the longest history of reliable use.

    **Kinetic** — converts resonance into motion, heat, and force. The workhorse band. Powers #{ref :kite_sail, "kites"}, runs refineries, generates electricity. The key mechanism is momentum nullification — kinetic-tuned ringglass can redirect opposing forces into a frequency null space, producing effectively unopposed motion. This is why a kite moves faster than wind alone should allow, and why resonance-powered vehicles don't obey normal friction constraints.

    **Signal** — carries information. Communication, data storage, navigation. In the wild, signal-frequency ringglass picks up and retransmits whatever data it encounters, which is why #{ref :echo_rivers, "Echo Rivers"} carry fragments of pre-Glassfall transmissions. Controlled signal-band arrays are used for communication, navigation, and — in the hands of the #{ref :echo_ledger_conclave, "Echo Ledger Conclave"} — recovering historical records from ambient noise.

    ### Bandwidth

    Within each band, the *bandwidth* of the application determines its power and accessibility. This is not a clean tier system — it's a continuum — but practitioners recognize three rough ranges:

    **Broad bandwidth** — wide, unfocused resonance. Easy to achieve, easy to maintain, limited in effect. This is what powers household devices: lanterns, stoves, compasses, basic heaters. Broad-bandwidth applications work with ambient resonance and low-grade ringglass. Anyone can use them. A broad structural application makes a wall stronger. A broad kinetic application heats a room.

    **Mid bandwidth** — focused resonance requiring trained #{ref :tuners, "Tuners"} or quality ringglass arrays. This is the professional range: kite engines, refinery operations, long-range communication, #{ref :clarisant, "Clarisant"}-grade attunement work. Mid-bandwidth applications produce the technology that runs the system's infrastructure. A mid kinetic application generates unopposed thrust. A mid signal application carries a conversation across a continent.

    **Narrow bandwidth** — tightly focused, poorly understood. Narrow-band resonance produces effects that don't have clear theoretical explanations. Structural narrow can locally alter physical laws. Kinetic narrow has been observed to produce translocation effects. Signal narrow borders on consciousness interface — direct information transfer without a medium.

    The narrow end is where the #{ref :elves, "elves"} operated routinely and where nobody else goes without extreme caution. #{ref :bloom_zones, "Bloom Zone"} relics, pre-Glassfall artifacts, and the deepest #{ref :the_shear, "Shear"} anomalies all exhibit narrow-bandwidth characteristics. The #{ref :lattice_proxy_synod, "Lattice Proxy Synod"}'s AI custodians appear to process information at narrow signal bandwidth, which is part of why communication with them is so difficult.

    Most people interact with mid-bandwidth resonance through manufactured devices — kites, communication arrays, industrial equipment — without understanding the tuning. Working professionals operate at mid *deliberately*. The difference is control, not exposure. Narrow is the domain of relics, accidents, and things nobody fully controls.

    **Single-wavelength resonance** — a theoretical limit beyond narrow. If narrow bandwidth is a tightly focused beam, single-wavelength is a perfectly coherent one: resonance at a single, exact frequency with no spread, no bleed, no interference. The analogy scholars use is light — broad bandwidth is a lantern, narrow is a focused beam, and single-wavelength is something like a thread of pure color, impossibly thin and impossibly intense. The #{ref :elves, "elves"} were reportedly working toward this before the #{ref :the_glassfall, "Glassfall"}. Certain pre-Glassfall artifacts exhibit behavior consistent with single-wavelength effects — perfect energy transfer with zero waste, structural alterations that violate known band boundaries, signal transmissions that appear to bypass medium entirely. Nobody alive can produce it. Nobody alive fully understands the theory. But it remains the outer horizon of what resonance could be: a single, perfectly coherent vibration that does exactly what the wielder intends and nothing else.
  PROSE
  prose <<~PROSE, section: :significance, heading: "The Geometry of Coherence"
    The band-and-bandwidth model is how working practitioners think about resonance, but it is not the oldest one. Long before the Tuners codified bands, resonance was understood through #{ref :the_three_forms, "The Three Forms"} — a cosmology built on the claim that a coherent vibration has a *shape*, and that to tune well is to help that vibration close into a stable figure. In that older language, the structural band is resonance closing toward one lawful figure and the kinetic band toward another, while the signal band is the undecided path between them. The single-wavelength horizon described above — perfect coherence, perfect closure — is what the Three Forms calls the One Truth. Most engineers regard the cosmology as picturesque rather than predictive. But its central intuition, that coherence is a kind of closure and incoherence a kind of failure to close, tracks the observed behavior of ringglass closely enough that it has never quite gone away.
  PROSE
  prose <<~PROSE, section: :sources, heading: "Ringglass"
    Resonance is ambient, but ambient resonance alone is too diffuse for most practical applications. To do useful work, it needs a medium that can concentrate, channel, and hold a frequency — and the best-known, most widely available, most reliable medium is #{ref :ringglass, "ringglass"}, the crystalline material the ring was built from, now scattered across the system as debris, sediment, and salvage. Ringglass is not the only material that interacts with resonance — certain mineral formations, deep-ocean water saturated with crystal particulate, and a handful of rare alloys exhibit varying degrees of resonant conductivity — but nothing else comes close in stability, tunability, or availability. For all practical purposes, resonance technology is ringglass technology. See the #{ref :ringglass, "ringglass entry"} for sourcing, grades, processing, and trade.
  PROSE
  prose <<~PROSE, section: :applications, heading: "Ambient Field"
    Most of Kaleidos and the inhabited ring has enough ringglass in the environment — soil, rock, building materials, the air itself — to sustain a low-level ambient resonance field. Household devices draw from this field the way a solar panel draws from sunlight. Lanterns, stoves, heaters, compasses, basic communication devices — all broad-bandwidth applications that work without external power as long as there's ringglass in the local environment. Which there almost always is.

    Settlements can amplify the local field using resonance concentrators — large ringglass arrays that collect and focus ambient energy into a denser local field. These aren't power plants. They're more like signal boosters. A settlement with a good concentrator has a richer resonance environment, which means household devices work better, mid-bandwidth applications are more reliable, and #{ref :tuners, "Tuners"} find the working conditions more comfortable.

    Drawdown is a real concern. Draw too much from a local field too quickly and the ringglass goes quiet until ambient energy replenishes. Settlements manage this through usage norms and, in larger cities, through #{ref :tempered_accord, "Tempered Accord"} resonance allocation frameworks that nobody enjoys dealing with.
  PROSE
  prose <<~PROSE, section: :limits, heading: "Limits"
    Resonance is not free energy. The ambient hum is real, but it's finite and local. Draw too much resonance from an area and the local field depletes — the ringglass goes quiet until the ambient energy replenishes, which can take hours, days, or weeks depending on how much crystal is in the local geology.

    The effects also degrade with distance from ringglass. Resonance doesn't broadcast well through open air. It travels through crystal, through crystal-laced rock, through water that's picked up crystal particulate. Move away from those media and the effect fades fast. This is why resonance technology requires physical ringglass components — you can't just wave your hands and channel it.

    And resonance is frequency-specific. A piece of ringglass tuned for structural reinforcement won't generate heat. A kinetic array won't carry signals. Retuning ringglass is possible but difficult, requires specialized equipment, and damages the crystal if done repeatedly. Most applications use purpose-cut pieces that do one thing well.
  PROSE
  prose <<~PROSE, section: :trade, heading: "Who Controls It"
    Nobody controls resonance itself — it's ambient, like weather. But the supply chain for refined ringglass is a different matter. See #{ref :ringglass, "Ringglass"}.
  PROSE
end

relate :rel_resonance_conducted_by_ringglass, :conducted_by, :resonance, :ringglass do
  prose "Resonance travels through #{ref :ringglass, "ringglass"} — through crystal, crystal-laced rock, and crystal-bearing water — and fades fast away from it, which is why all resonance technology is ringglass technology."
end
