# Schema — generated by tools/import.rb (taxonomy from snapshot; tags from tags.md).
schema do
  entity_type :ability, :artifact, :concept, :conflict, :creature, :culture, :era, :faction, :geographic_location, :incident, :installation, :npc, :phenomenon, :resource, :species, :transport
  entity_type :loop, :theme, :thread, wiki: false

  effect :set ; effect :clear ; effect :create ; effect :destroy ; effect :transfer

  relation :active_during, category: :causal, temporal: false
  relation :attuned_to, category: :technical, temporal: false
  relation :at_stage, category: :narrative, temporal: false
  relation :born_in, category: :social, temporal: false
  relation :built, category: :technical, temporal: false
  relation :carries, category: :social, temporal: true
  relation :caused, category: :causal, temporal: false
  relation :caused_by, category: :causal, temporal: false
  relation :causes, category: :causal, temporal: false
  relation :chairs, category: :organizational, temporal: true
  relation :commemorates, category: :social, temporal: false
  relation :conducted_by, category: :technical, temporal: false
  relation :cooperates_with, category: :social, temporal: true
  relation :created, category: :causal, temporal: false
  relation :created_during, category: :causal, temporal: false
  relation :depends_on, category: :technical, temporal: false
  relation :derived_from, category: :technical, temporal: false
  relation :designed, category: :technical, temporal: false
  relation :destroyed, category: :causal, temporal: false
  relation :disappeared_during, category: :causal, temporal: false
  relation :embodies, category: :narrative, temporal: false
  relation :emerged_during, category: :causal, temporal: false
  relation :employed_by, category: :organizational, temporal: true
  relation :extends, category: :meta, temporal: false
  relation :fills_beat, category: :narrative, temporal: false
  relation :founded_in, category: :spatial, temporal: false
  relation :governed_by, category: :organizational, temporal: true
  relation :governs, category: :organizational, temporal: true
  relation :has_archetype, category: :classification, temporal: false
  relation :has_beat, category: :narrative, temporal: false
  relation :has_stage, category: :narrative, temporal: false
  relation :headquartered_in, category: :spatial, temporal: true
  relation :hiding_from, category: :dm, temporal: false
  relation :hosts, category: :spatial, temporal: true
  relation :inhabits, category: :social, temporal: true
  relation :inner_of, category: :spatial, temporal: false
  relation :in_orbit_of, category: :spatial, temporal: false
  relation :leads, category: :organizational, temporal: true
  relation :located_in, category: :spatial, temporal: true
  relation :maintains, category: :social, temporal: true
  relation :manifests_at, category: :spatial, temporal: false
  relation :member_of, category: :organizational, temporal: true
  relation :mentions, category: :meta, temporal: false
  relation :on_surface_of, category: :spatial, temporal: false
  relation :operates_in, category: :spatial, temporal: true
  relation :orbits, category: :spatial, temporal: false
  relation :originated_in, category: :causal, temporal: false
  relation :owned_by, category: :organizational, temporal: true
  relation :participated_in, category: :causal, temporal: false
  relation :part_of, category: :spatial, temporal: false
  relation :possesses, category: :social, temporal: true
  relation :powers, category: :technical, temporal: false
  relation :practiced_by, category: :social, temporal: true
  relation :regulates, category: :organizational, temporal: true
  relation :related_to, category: :banned, temporal: false
  relation :resonates_with, category: :narrative, temporal: false
  relation :seeping_through, category: :dm, temporal: false
  relation :sourced_from, category: :technical, temporal: false
  relation :studies, category: :social, temporal: true
  relation :supplies, category: :organizational, temporal: true
  relation :taught, category: :social, temporal: false
  relation :terminus_of, category: :spatial, temporal: false
  relation :trains, category: :organizational, temporal: true

  tag :AI, "Artificial intelligence, custodian systems"
  tag :activism, "Political resistance, reform movements"
  tag :archives, "Record-keeping, history preservation, memory"
  tag :catastrophe, "Destructive events"
  tag :cosmology, "The fundamental order of reality; metaphysics of resonance, the Three Forms, the wider cosmic order"
  tag :danger, "High-risk environment or situation"
  tag :diplomacy, "Inter-faction or inter-settlement negotiation"
  tag :divergence, "Cultural drift between isolated communities"
  tag :ecology, "Environmental stewardship, conservation"
  tag :"fluid-reality", "Physics/reality is loosened or mutable at this location"
  tag :founding, "Origin events, establishment"
  tag :governance, "Political systems, authority structures, law"
  tag :household, "Everyday items, domestic technology"
  tag :isolation, "Signal Famine era disconnection"
  tag :"kinetic-freq", "Mid-band resonance; motion, heat, force"
  tag :legend, "Passed into myth; historicity debated by general population"
  tag :materials, "Physical resources, raw or processed"
  tag :military, "Armed forces, warships, defense"
  tag :music, "Music as cultural or structural force"
  tag :mystery, "Unexplained gaps, unsolved questions, active investigation"
  tag :navigation, "Wayfinding, piloting, route knowledge"
  tag :orbital, "In orbit, the ring, or the Shear"
  tag :origin, "Origin story or inciting incident for current state"
  tag :"outer-system", "Beyond Kaleidos orbit"
  tag :rebuilding, "Reclamation-era reconnection and reconstruction"
  tag :religion, "Belief systems, spiritual practice"
  tag :resonance, "Involves the resonance energy system"
  tag :"ring-era", "Predates the Glassfall; original builder technology"
  tag :"ring-hab", "A habitat on the Glass Frontier ring fragments"
  tag :ringglass, "Involves ringglass as a material or commodity"
  tag :salvage, "Shear salvage operations, scavenging"
  tag :"signal-freq", "High-band resonance; communication, data, memory"
  tag :"social-structure", "Class, caste, citizenship, social hierarchy"
  tag :species, "Intelligent species, biology, racial characteristics"
  tag :"structural-freq", "Low-band resonance; reinforcement, building"
  tag :surface, "Located on Kaleidos's planetary surface"
  tag :trade, "Commerce, supply chains, economics"
  tag :training, "Education, apprenticeship, attunement learning"
  tag :transport, "Ships, trade routes, logistics infrastructure"
  section_heading :access
  section_heading :aesthetics
  section_heading :aftermath
  section_heading :applications
  section_heading :atmosphere
  section_heading :biology
  section_heading :cause
  section_heading :course
  section_heading :culture
  section_heading :dangers
  section_heading :description
  section_heading :economy
  section_heading :function
  section_heading :geography
  section_heading :governance
  section_heading :history
  section_heading :how_it_works
  section_heading :implications
  section_heading :language
  section_heading :legacy
  section_heading :limits
  section_heading :mechanics
  section_heading :naming
  section_heading :operations
  section_heading :origin
  section_heading :people
  section_heading :perception
  section_heading :present_day
  section_heading :public_profile
  section_heading :reference
  section_heading :relationships
  section_heading :resonance
  section_heading :resources
  section_heading :significance
  section_heading :sources
  section_heading :structure
  section_heading :tensions
  section_heading :the_third_panel
  section_heading :trade
  section_heading :traits
  section_heading :truth
  section_heading :usage_notes
  section_heading :values
end
