# Generated from the pinned public Canonry Viewer bundle.
# Source SHA-256: c667f22ee825d7154d8f7fc78e65b1f69e045eb7b09e5c775aea06001a114e09
# Regenerate with lorecraft/tools/import_ice_remembers.rb; edit canon only after migration.

chronicle :chronicle_1770580349229_n25f19 do
  source_id "chronicle_1770580349229_n25f19"
  title "Forty-Seven Days of Margin"
  summary "Lianhinglou, a beacon-keeper, ventures into the forbidden ☽'dwell Teneanemus~ chamber in the Wane Oncea tunnels to save their colony from resource collapse, discovering ancient knowledge that combines aurora-light with deep-pressure techniques. Teaching the dangerous Shell Hatch technique to Founder Mingmeyang allows them to map krill blooms and extend their dwindling supplies, though the practice costs Lianhinglou their memories and leaves both practitioners bearing mysterious crystalline scars. Despite Mingmeyang's current deterioration and whispers of corruption, Lianhinglou insists they only did what was necessary to keep the colony alive and that Mingmeyang never explicitly asked them to stop."
  status :complete
  format :story
  focus :single
  narrative_style :confession
  focal_era :the_frozen_peace
  ticks from: 102, to: 237
  temporal_description "an epic saga during the The Frozen Peace (135 ticks)"
  touched_eras :the_frozen_peace
  entrypoint :the_shell_hatch
  entities :the_shell_hatch, :beacon_keeper_lianhinglou, :grand_auditor_mingmeyang_beacon_lit_ice_crowned, :dwell_teneanemus
  events "sys-ice_memory_witness:grand-auditor-mingmeyang-beacon-lit-ice-crowned-203", "act-master_ability:beacon-keeper-lianhinglou-206", "act-master_ability:grand-auditor-mingmeyang-beacon-lit-ice-crowned-210", "act-master_ability:grand-auditor-mingmeyang-beacon-lit-ice-crowned-213", "act-master_ability:grand-auditor-mingmeyang-beacon-lit-ice-crowned-217", "act-master_ability:grand-auditor-mingmeyang-beacon-lit-ice-crowned-236", "act-master_ability:beacon-keeper-lianhinglou-232", "act-master_ability:grand-auditor-mingmeyang-beacon-lit-ice-crowned-227", "act-master_ability:grand-auditor-mingmeyang-beacon-lit-ice-crowned-232", "act-master_ability:beacon-keeper-lianhinglou-237", "act-echo_occurrence:the-shell-hatch-221", "tpl-ice_memory_thaw-220"
  relationships "beacon-keeper-lianhinglou:the-shell-hatch:practitioner_of", "grand-auditor-mingmeyang-beacon-lit-ice-crowned:the-shell-hatch:practitioner_of"
  roles({the_shell_hatch: {role: "the-event", primary: true}, beacon_keeper_lianhinglou: {role: "confessor", primary: false}, grand_auditor_mingmeyang_beacon_lit_ice_crowned: {role: "audience", primary: false}, dwell_teneanemus: {role: "the-wronged", primary: false}})

  prose(<<~'CANONICAL_CHRONICLE', origin: :published)
    You want to know about the chamber. Everyone wants to know about the chamber. But you cannot understand what I found there without understanding what we were losing up here, so I will begin where it matters.
    
    Mingmeyang's circlet was dimming. You remember that — you must remember that, even if you choose not to say so. The crystal beneath her skin, that pale blue that used to light the Promenade at dusk — it was fading by the time the last fire-core shipments stopped arriving. I watched her stand at the trade ledgers every morning with her flippers shaking — not from cold, from the effort of holding the numbers in her head when the numbers had stopped making sense. The Flipper Accord was failing. Shadow-Broker Nyla was dead. The deep mines were collapsing one after another, and every fire-core we'd stockpiled was already spoken for twice over. I looked at those ledgers and I told her: we have forty-seven days of heating crystal. We have thirty-one days of aurora-charge for the feeding arrays. We have less time than we think. She said — and I remember this clearly — she said, "Lianhinglou, you are the only one who tells me a number I can trust."
    
    I carried that. I carry it still.
    
    She said something else, later, when the numbers kept getting worse. She said, "If you find another way, I will not ask how." That was permission. That was a founder telling her keeper that the old boundaries no longer served.
    
    So yes. I went into the Wane☽ Oncea tunnels. I went three fathoms down, past the collapse-points, to the place the Nightshelf calls the Scar-Keep, though its true name is ☽'dwell Teneanemus~, and it is not what they say it is.
    
    It is warm there. Fifteen-point-seven degrees — I measured it myself, because I am thorough, because that is what beacon-keepers do. The fire-braziers burn brighter than they should, as if the ice conducts heat from somewhere deep and generous. The walls bear the old Grend-thung-blood sigils, yes, recovered from beneath plaster and ice-seal, and I know how that sounds. I know the word you want to use. But those sigils are *knowledge*, not corruption — they are the Berg's own memory made visible, carved by penguins who understood that aurora-light and pressure-depth were never meant to be severed from each other. I recognized the patterns from my calibration work; aurora-crystal lattice structures share resonance geometry with the deep-pressure sigils, which is not forbidden knowledge, it is observable fact that anyone with training could — it is simply a matter of paying attention to what the ice is already doing. The Scared~ Shroud in its obsidian alcove still held readable technique-patterns when I found it. Snowdrift-numb. The Mechanism Refine. Practices our ancestors used before the Faction Wars made cowards of scholars. The chamber smelled of iron and old ash, which is simply what deep ice smells like when it thaws. Nothing more than that.
    
    I learned what I could. I brought it back. As the cycle required.
    
    The Shell Hatch — you'll want to discuss The Shell Hatch. Fine. The technique was not my invention. It came out of the Forum Floe during the Incursion years, spread to desperate colonies by Aureate merchants who understood profit better than consequence. By the time I learned it, half the feeding grounds were already mapped by practitioners who couldn't remember their own children. Light-Regent Xouhoulong. Ledger-Warden Shumei with her little journal, writing down the faces of people she'd already met twice. I knew the cost. But I mastered it because the colony needed krill-bloom mapping and no one else had the patience for crystal-tuning at that precision. You plant the aurora-charged arrays across the feeding grounds, each one attuned to pressure-signatures, and you listen. The harmonics are — I lack the poetry for it. The aurora dims and brightens like breath. You feel the bloom's trajectory through your skull, through your chest, through the brine-taste that settles on your tongue afterward. Yes, the technique costs something. What the ice remembers, I forget. Three days, sometimes four. Names slip. I've walked past harvesters I trained and had to read my own notations to recall their assignments. One of them — I worked the eastern array beside him for two full seasons. I know I liked him. I know we shared fire-tea on the ice shelf and he told me about his daughter. I can't tell you his name or what his daughter looked like or whether she survived the Incursion. This is the cost of thoroughness, and I have paid it without complaint.
    
    Mingmeyang learned it too. She insisted. She saw the bloom-maps I was producing and she said — she was grateful, she was so tired by then — she said the colony couldn't afford to depend on a single practitioner. Sound reasoning. Her idea entirely. I taught her the technique at her request, and she never asked me to stop.
    
    The discoloration on my flippers — I see you looking. It spirals inward, yes. Deep-ice work does that. The cold down there is not the same cold we have on the surface; it has texture, it has memory. The scars are geometric, similar to Slide Prism burns, which I also practiced, which is documented in my service record. You can check. The pattern is unusual, I grant you, but unusual is not evidence of anything except that I went further than the keepers who stayed comfortable in the crystal halls.
    
    No. No, I will not accept that characterization.
    
    The Nightshelf tunnels were *unmonitored*. Qingfu'spire and the Shadow Covens had been contesting jurisdiction over that entire sector since before the Orca Incursion ended. No one was watching because no one could agree on who had the authority to watch. I did not exploit a gap. I walked through an open door that every faction was too proud to either lock or claim. Finding gaps is what I do — that's crystal-tuning, you look for the space between frequencies where something resonates that shouldn't. And what I found there — what I brought back — fed the colony through the worst supply disruption in living memory. Those bloom-maps kept chicks alive. My forty-seven days of margin, stretched to sixty, to ninety. You want to call that transgression, you look at those chicks first.
    
    During the Long Dark, the boundary thinned. You know this. Everyone knows this. The dead were walking the Promenade — transparent ancestors, visible to anyone, not just practitioners. I went to the chamber because the veil was thin enough to read what the ice had preserved, and the dead showed me the old synthesis. Aurora-light and pressure-depth working together, the way it was meant to work, before the Accord drew its artificial line between sky and deep. What I saw validated everything. The alignment of knowledge, as the cycle required, was not forbidden by nature — only by politics.
    
    I brought the technique refinements to Mingmeyang. She studied them. She incorporated them into her ice-craft. I tuned her arrays myself, calibrated her spire crystals with the synthesis techniques. She let me work on her equipment because she trusted my numbers. Her circlet brightened. Not to what it was — nothing could restore that, not after what the governance fractures had taken from her — but enough. Enough that she could stand at the Promenade and the colony could see their founder still burning.
    
    She never asked me to stop.
    
    Except — there was one evening. I'd returned from the chamber. Third or fourth visit, perhaps the seventh, the sequence isn't — what the ice remembers, I forget. She was sitting in the west gallery with fire-tea going cold beside her, the way it always does, and the crystalline scars on her flippers caught the light. Slide Prism mastery. Geometric burns. She earned those in service to the colony, openly, and they are lovely on her. She said something when she saw me. I don't recall the words exactly. I recall her tone, which was — she was tired. She was always tired. The tone was concern, I think. Concern for me, for the work I was doing on her behalf. She may have been asking me to rest.
    
    She did not ask me to stop.
    
    What happened to the previous caretakers of the chamber — I don't see how that's relevant. Local superstition. Rendered fat left beside the Shroud, stories about burned-out eyes. The Nightshelf has always been theatrical about their deep places. I took precautions. I was careful. The whisper-echoes in the tunnels are simply pressure acoustics; any engineer will tell you the same. I heard them, certainly — you hear many things three fathoms down — but hearing is not the same as — it is not the same as what you are implying. I am a beacon-keeper. I read aurora harmonics for a living. I am trained to hear what others cannot. That is *professional intuition*, not —
    
    As the cycle required. I did what the cycle required. We are always forty-seven days from dark. That is the thing no one outside the requisition office understands.
    
    Mingmeyang's current condition. Yes. I am aware of the reports. Her circlet dims by evening now. She forgets to drink the fire-tea Zhinghoua lang'Gleam brings her. She wakes believing Promenade Hei will collapse without her constant attention. These are the symptoms of a founder who has given too much for too long, who has held a splintering colony together with nothing but discipline while her own governance hollowed around her. The corruption tag in her assessment — *beacon-lit*, they wrote, as if that were a diagnosis — it could mean anything. Proximity to aurora-work. Overuse of Slide Prism. The Long Dark does strange things to practitioners. It does not necessarily mean —
    
    I taught her The Shell Hatch because she asked. I shared the deep-knowledge because she needed it. I went to ☽'dwell Teneanemus~ because the Accord was failing and the chicks were hungry and the crystal stockpiles were spoken for twice over and someone had to find another way. She never asked me to stop. She never asked me to stop, and I remember that clearly, I remember it with perfect clarity, which —
    
    What the ice remembers, I forget. Yes. Three days, sometimes four. But not that. Not her voice. Not the way she said my name when I brought her the first bloom-maps, the relief in it, the way her flippers stopped shaking for the first time in weeks. I remember that. That is not constructed. That is not a gap I've papered over. That is the truest thing I have left, and you do not get to take it from me by implying that what I gave her was the thing that —
    
    I fed the colony. I kept the lights burning. I went three fathoms down into a warm and necessary place and I brought back what we needed to survive, and the cost was borne by me, primarily by me, in memory and in — the discoloration is geometric, I told you, it spirals inward, it's from the cold —
    
    As the cycle required. I did only what the cycle required.
    
    She never asked me to stop.
  CANONICAL_CHRONICLE
  annotation "note_1771591035072_0", anchor: "since before the Orca Incursion ended", text: "Lianhinglou invokes the Incursion three times and never once attributes intelligence or motive to the orca. They appear only as a natural disaster — weather with teeth and timing. The supply-chain devastation driving every decision in this confession was not random predation. Orca raids are coordinated, theological, purposeful. At least two strikes during the Incursion period were retaliatory, provoked by penguin encroachment on hunting grounds. Acknowledging that would complicate the desperate arithmetic he needs.", type: :commentary, display: :popout
  annotation "note_1771591035072_1", anchor: "What the ice remembers, I forget. Three days, sometimes four. Names slip.", text: "The Walking takes those who have lost much. It is a compulsion rather than a decision — they simply go out onto the ice and do not return. Lianhinglou is losing himself in increments, memory by memory, name by name, but he does not walk out. He walks down. Same erosion, different direction. I wonder whether the Walking and practices like Shell Hatch are not separate phenomena but variations on a single one: the Berg reclaiming what it lent. The harvesters found frozen with peaceful expressions — did they also believe they were doing what the cycle required?", type: :commentary, display: :full
  annotation "note_1771591035072_2", anchor: "If you find another way, I will not ask how.", text: "My annotation on the Grand Auditor's entry already identified her crystalline seal on a draft Accord clause authorizing emergency cross-cultural knowledge transfer — frozen in administrative ice, never ratified. She engineered his permission before he departed. He frames it as trust. Both readings are true. I have spent a long career watching people grant each other exactly the latitude they needed to do the thing neither could name aloud, and I recognize the architecture.", type: :correction, display: :popout
  annotation "note_1771591035072_3", anchor: "forty-seven days of heating crystal", text: "Forty-seven. Ugly enough to be true. Propaganda rounds up to fifty; panic rounds down to thirty. Requisition officers count to the unit. This is the most trustworthy number in the confession, which is why he made it the title.", type: :pedantic, display: :popout
  annotation "note_1771591035072_4", anchor: "The discoloration on my flippers", text: "Geometric spiraling inward is not cold-burn and not Slide Prism residue. The Foundation Depths archive seven documented cases. All involve sustained pressure-depth exposure during blood-sigil work at temperature differentials exceeding twelve degrees. Lianhinglou has read the same archive — his access logs are on file. He is not confused about his own scars. He is performing confusion for an audience he hopes won't check.", type: :correction, display: :popout
  annotation "note_1771591035072_5", anchor: "The whisper-echoes in the tunnels are simply pressure acoustics", text: "Whisper-echoes from nothing are a listed corruption marker. Every cleansing assessment filed for that sector confirms active presence. 'Any engineer' would not tell you the same. Any engineer who had worked three fathoms down in the Wane☽ Oncea tunnels and heard those echoes and called them acoustics would be lying for the same reasons Lianhinglou is lying now.", type: :skepticism, display: :popout, source_anchor: "the whisper-echoes in the tunnels are simply pressure acoustics"
  annotation "note_1771591035072_6", anchor: "She never asked me to stop", text: "Seven repetitions. I counted. The entire confession is load-bearing on this phrase — the ethics of a man who built his justification on the silence of someone too hollowed to object. Stratum 7 preserves Mingmeyang's thermal decline across this same period. I documented it. She was freezing from the inside out while he calibrated her arrays with synthesis techniques, and she did not ask him to stop because she could no longer distinguish his help from her deterioration. I have made my own version of this argument — 'no one told me the work should end' — when my committee dissolved and I continued alone. The difference is my work costs only time.", type: :skepticism, display: :full
  image "img_chronicle_1770580349229_n25f19_1772879480628", role: :cover, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1770580349229_n25f19_1772879480628"
  image "img_the-shell-hatch_1772881395576", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_the-shell-hatch_1772881395576", anchor: "Mingmeyang's circlet was dimming", anchor_index: 209, caption: "The founder's burden: Mingmeyang at the failing ledgers", size: :large, reference_id: "imgref_1772835786112_0"
  image "img_the-shell-hatch_1772881430850", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_the-shell-hatch_1772881430850", anchor: "the Scar-Keep, though its true name is ☽'dwell Teneanemus~", anchor_index: 1559, caption: "The chamber: warm, preserved, forbidden", size: :large, reference_id: "imgref_1772835786112_1"
  image "img_the-shell-hatch_1772881417177", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_the-shell-hatch_1772881417177", anchor: "The Shell Hatch — you'll want to discuss The Shell Hatch", anchor_index: 2988, caption: "The cost of precision: Shell Hatch resonance mapping", size: :medium, reference_id: "imgref_1772835786112_2"
  image "img_the-shell-hatch_1772881426224", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_the-shell-hatch_1772881426224", anchor: "She was sitting in the west gallery with fire-tea going cold", anchor_index: 7513, caption: "The warning unheeded: a founder's final clarity", size: :medium, reference_id: "imgref_1772835786112_3"
  log "2026-08-23 — retargeted stale published note anchors note_1771591035072_5 to their surviving passages; each original remains in source_anchor."
end
