# Generated from the pinned public Canonry Viewer bundle.
# Source SHA-256: c667f22ee825d7154d8f7fc78e65b1f69e045eb7b09e5c775aea06001a114e09
# Regenerate with lorecraft/tools/import_ice_remembers.rb; edit canon only after migration.

chronicle :chronicle_1770546814545_i5p4n3 do
  source_id "chronicle_1770546814545_i5p4n3"
  title "Sharp Cracks at Dawn"
  summary "During Tide Custom festival in the Aurora Stack, a mysterious ice fracture occurs beneath the Promenade Ward, and Aishouwa, a Stack soldier, attempts to draw her blade against the Nightshelf emissary ☽'velumae and a Crypt-seal artifact. Three conflicting accounts reveal the truth: civic recorder Lianheizhi presents an official narrative of a stable festival interrupted by geological chance, soldier Skael'Frost describes a deliberate confiscation ordered by Plunge-Caller Oeichowei, and trader ☽'velumae exposes that the ice was already corrupted by the sealed artifact buried beneath the promenade for weeks, with the crack originating from deep structural failure rather than surface events. The three testimonies are filed without cross-examination, allowing the colony's leadership to maintain the official story while the underlying corruption—economic collapse, depleted reserves, and the artifact's dark magic—remains unacknowledged."
  status :complete
  format :story
  focus :single
  narrative_style :rashomon
  focal_era :the_frozen_peace
  ticks from: 201, to: 233
  temporal_description "an extended arc during the The Frozen Peace (32 ticks)"
  touched_eras :the_frozen_peace
  entrypoint :thaw_frost_scarred
  entities :thaw_frost_scarred, :the_fawned_crypt_seal, :the_promenade_ward, :aishouwa_beacon_lit_the_frost_bane, :tide_custom
  events "act-corrupt_location:grrul-kzul-strike-225", "act-occurrence_marks_artifact:the-mbra-silentiu-231", "tpl-colony_founding-201", "tpl-economic_colony_decline-226", "act-occurrence_marks_artifact:thaw-frost-scarred-230", "act-occurrence_marks_artifact:the-pta-extinct-233"
  relationships "thaw-frost-scarred:the-promenade-ward:epicenter_of", "thaw-frost-scarred:the-promenade-ward:triggered_by", "the-fawned-crypt-seal:thaw-frost-scarred:participant_in", "tide-custom:thaw-frost-scarred:commemorates"
  roles({thaw_frost_scarred: {role: "the-moment", primary: false}, the_fawned_crypt_seal: {role: "witness-a", primary: false}, the_promenade_ward: {role: "witness-b", primary: false}, aishouwa_beacon_lit_the_frost_bane: {role: "witness-c", primary: false}})

  prose(<<~'CANONICAL_CHRONICLE', origin: :published)
    **Lianheizhi (ice-remembered) Vorwi'Seal**
    
    The aurora burned clear. I will say this until the ice itself corrodes, because it is the fact on which all others depend: the aurora burned clear that cycle, the clearest it had burned since Yahailong's founding-calculation, the spires drinking light so deep their crystal faces flushed violet, then white, then a color we have no word for because we've only seen it twice. Tide Custom cannot proceed under clouded skies. The sky was not merely unclouded. The sky was judgment rendered in radiance, and it found us worthy.
    
    The Promenade Ward at peak festival is a thing you must witness from the upper galleries to understand. The geometry matters — the spires arranged so each catches the aurora at a fractionally different angle, the light cascading downward through the crowd in measured waves, so that every penguin on the promenade stands illuminated by a slightly different hue. We look like what we are: a spectrum, a colony proving its fitness. Merchants had unfurled aurora-silk along the main approach, bolts of it glowing in wavelengths the lower shelves will never see, and the candidates had begun their gifting — fire-cores passed claw to claw through the crowd, each one a month of warmth someone chose to spend because Tide Custom demands that worthiness be visible. A leader who won't burn reserves in the sight of the people has no right to hoard them in private.
    
    Aishouwa stood near the Nightshelf delegation. I noted this because her ice-plate armor caught the spire-light in a way that marked her position precisely — she was between the emissary and the eastern gallery, angled so her body made a wall. The ☽'micseleia' Dagger was sheathed. The Nightshelf emissary — the trader ☽'velumae — had presented the Fawned~ Crypt-seal as a formal offering under the Accord's emergency provisions, an artifact-loan to stabilize the Ward's fracture systems during the market contraction. Unusual, certainly. Provocative in its optics. But sanctioned. I reviewed the notation myself.
    
    Then the ice cracked.
    
    The sound came from everywhere and nowhere, the way ice-fractures do when the fissure runs deep enough to resonate through the whole structure. The crowd surged toward the exits — bodies compressing at the gallery mouths, the silk displays trampled, three fire-cores dropped and rolling free on the promenade. Aishouwa's response was immediate. She raised the blade — drew it clean, one motion — and placed herself between the emissary and the crowd. Protection. The gesture of a soldier trained in the reconstruction years, when Aurora Stack and Nightshelf first learned to stand in the same space without drawing blood.
    
    "Hold your positions," she said. Clear. Calm. The formal phrasing of a Stack defender addressing civilians. "The spires are stable."
    
    The emissary was unharmed. The Crypt-seal was secured. The festival was not completed, but Tide Custom's provisions allow for geological interruption without dishonor. What followed — the economic collapse, the supply fractures, the quiet starvation — was the Thaw's doing, not the festival's. The aurora was clear. The Custom was clean. What the ice broke, the ice broke on its own.
    
    
    **Ingchushei (rime-singer) Skael'Frost**
    
    Twelve paces from Aishouwa. Six from the nearest exit — the eastern gallery mouth, width of four penguins abreast, narrowing to two where the old ice-supports jut inward. I kept the exit in my peripheral because that's the job, and because I'd walked the Promenade's evac routes during reconstruction when the corridors were still half-collapsed and you learned to count your distances or you died in the crush. Distances first; then the rest.
    
    The aurora was dimming. Had been dimming for a quarter-cycle before the festival opened, a slow drain anyone stationed at spire-level could see in the crystal output — the facets shifting from white down through pale violet into the murky amber that means the light is thinning. Tide Custom should have been cancelled. Clouded skies cancel everything; diminishing aurora doesn't technically qualify, because the old provisions never imagined this specific failure. So the festival opened on a technicality, and the candidates gifted fire-cores the colony could not afford to burn, and the silk went up, and the crowd filled the promenade, and nobody on the upper galleries said a word because cancellation would mean admitting the reserves were already ash.
    
    I watched Aishouwa's flippers. Colony blood dried brown on the left, crusted in the joint where the flipper meets the bracer. Not fresh. Hours old at least. She'd come from somewhere before the ceremony — somewhere that had cost someone — and hadn't cleaned up. Or hadn't been permitted to. Her grip on the ☽'micseleia' Dagger was wrong. I trained alongside her in the reconstruction; I know her draw like I know my own breathing. Ritual grip is loose fingers, a slight roll of the wrist, the hilt settling into position by habit. That day her grip was locked. Knuckles pale beneath the down. Somebody had told her to be ready, and she was ready in the way you're ready when the order's already been given.
    
    Plunge-Caller Oeichowei stood behind the second spire, just past the sightline from the upper galleries. Not hidden — positioned. The angle meant the civic observers couldn't see the gesture, but I was twelve paces out and low, and I saw Oeichowei's flipper drop. A signal. Not subtle; not meant to be subtle to anyone at blade-level.
    
    Aishouwa raised the blade.
    
    Not toward the crowd. Toward the Nightshelf delegation. One clean motion, the dagger's edge catching what was left of the dying aurora, and ☽'velumae stepped back — smart — while Aishouwa said something I will render exactly: "Step away from the seal." Not *hold your positions*. Not a defender's phrasing. A confiscation.
    
    The Crypt-seal was found on the Nightshelf trader's person when the guards searched the delegation after the crack. Wrapped in aurora-silk to mask the pressure-depth signature, tucked against the body where the cold would read as natural. Smuggled into the heart of the Ward during Tide Custom, when every eye was on the gifting and every guard was managing crowd flow. A Nightshelf artifact sealed in obsidian and ancestor bone, radiating the kind of deep-magic the Stack considers taboo, sitting in our market-space during the worst economic fracture in living memory.
    
    The ice cracked because the ice was already broken. The festival was a painted shell over a starving colony, and someone used the crowd as cover. Aishouwa did what she was ordered to do. That is not heroism; it is not treason; it is a soldier following the only chain of command she had left. The blood on her flippers was already dry. What the ledgers don't record is that she didn't hesitate. Not even the half-second that might have mattered.
    
    
    **☽'velumae**
    
    Three fire-core braziers line the main promenade. Standard installation — two along the eastern approach, one at the gallery junction. That cycle, two were cold. Not depleted; pulled. The mounting brackets still held warmth-memory, which means the cores were removed within the last eight hours, deliberately, by someone who knew the brackets would betray the timing. You pull a fire-core from a public brazier during Tide Custom and you are either stealing warmth from the festival or ensuring no one notices the cold that's already there. Either way, you are managing a secret.
    
    I was present under Accord terms: quarterly crystal delivery, standard weight, standard grade. The Nightshelf's clocks are water-calibrated; the Stack's are aurora-calibrated. The discrepancy is known, and it is not my concern that their observers mistake precision for haste. The Promenade Ward's receiving ledgers would show my name, my cargo manifest, and the time-stamp of my arrival at the eastern gallery. What the ledgers don't record is what I saw in the ice beneath the promenade.
    
    Tide Custom is an astonishing thing to witness from below. The aurora-silk alone — nine bolts on display, each representing three to five months of crystal-charging labor, unfurled for an audience that would never buy them. Eight aurora fragments to display. Three to watch from the mid-terrace. Free to stand below and look up. The booths were magnificent, and the geometry was precise, and none of it was meant for anyone at trading-floor level.
    
    The Fawned~ Crypt-seal was not offered. The Fawned~ Crypt-seal was not smuggled. The Fawned~ Crypt-seal was already there — half-buried in the corrupted ice beneath the eastern walkway, its obsidian casing visible only from trading-floor level where the aurora-light hits at the angle the surface-dwellers never use. The ice had been fracturing for weeks along fourteen distinct corruption-threads, each one claw-width and spreading outward from the point where the seal sat in the deep ice, and I counted them because counting is what I do when the numbers above the surface stop making sense.
    
    Dark threads in the ice. Fourteen. Radiating. The cold-burn discoloration the Stack calls background; the Nightshelf calls warning.
    
    When the crack came, it came from below. I felt it through my feet — a deep-ice shudder, the kind that means a pressure vein has shifted and the structure above it is suddenly negotiable. Beneath the groan, a hiss — pressurized air escaping from below, carrying the smell of something sweet and wrong. The surface penguins felt the floor breaking. I felt the floor breathing.
    
    Aishouwa's flipper went to the hilt of the ☽'micseleia' Dagger. This I saw — close enough to see the frost-rime on the sheath, the crystal of cold-seep that had bled upward from the corruption and locked the blade shut. She pulled. The sheath held. She pulled again. The blade did not come free. What looked like a clean draw from twelve paces, through aurora-silk and panic and the crowd's compression, was a penguin trying to arm herself and failing, her flipper locked on a hilt that would not give, the dried blood on her bracer-joints cracking as she strained.
    
    She said nothing. Not *hold your positions*. Not *step away from the seal*. Her beak opened; the sound was lost in the cracking ice and the crowd's scream, and I was close enough to see her eyes, and her eyes were not calm and not commanded. Her eyes were afraid.
    
    The ice beneath the festival was already sick. The corruption was not caused by the Thaw, and the Thaw was not caused by the festival, and the festival did not cause the corruption. These three things happened simultaneously because they had been happening for longer than anyone who profits from the Promenade Ward would willingly admit. What the ledgers don't record, what the spires don't catch, what the blade-watchers can't see from their exits and angles — the ice remembers, and the ice was already speaking, and nobody at trading-floor level was important enough to hear.
    
    
    Lianheizhi finished the account at third-bell. Clean copy, formal register, filed under the Tide Custom proviso for geological interruption. He set his seal in aurora-wax and placed it in the testimony stack beside the two others he had not read and would not read, because a civic recorder reviews his own observations, not the peripheral impressions of soldiers and foreign traders.
    
    On the desk beside his writing instruments: the Ward's fire-core inventory for the coming quarter. The seal on the envelope was unbroken. He placed his testimony on top of it, straightened both documents until their edges aligned, and went to the window where the aurora — clear, still clear, it had been clear — lit the spires in colors he could name and catalogue and trust.
    
    The two cold braziers on the promenade below were visible from this height only as dark spots in the light-pattern. He did not look down.
  CANONICAL_CHRONICLE
  annotation "note_1771591369178_0", anchor: "the aurora burned clear that cycle, the clearest it had burned since Yahailong's founding-calculation", text: "Spire crystals retain aurora-light impressions for decades. The facets Lianheizhi describes — violet, then white, then beyond naming — would still be readable in the crystal lattice. So would Skael'Frost's slow drain from white through pale violet into murky amber. These are not compatible observations. One of them is recorded in the spires right now, testable by any adept with a calibration lens. How extraordinary that no one has checked. How entirely predictable.", type: :correction, display: :full
  annotation "note_1771591369178_1", anchor: "the Accord's emergency provisions", text: "Which version? The public Flipper Accord contains no artifact-loan provision. The second secret renegotiation — depth-stratum 4, administrative ice — included a clause permitting 'material stabilization transfers' during structural emergencies, struck before signing. Lianheizhi reviewed a notation that authorized something the published Accord does not permit. Either he had access to a draft that should not exist at civic-recorder clearance, or someone forged the authorization. He does not seem curious about this.", type: :skepticism, display: :full
  annotation "note_1771591369178_2", anchor: "Colony blood dried brown on the left, crusted in the joint where the flipper meets the bracer", text: "The ☽'micseleia' Dagger chose Aishouwa as wielder, and — per every account I have cross-referenced — the weapon has drawn more penguin blood than orca. Hours-old colony blood, before a public ceremony. Skael'Frost sees this and reads preparation. I read aftermath. Someone bled for this festival to proceed.", type: :skepticism, display: :popout
  annotation "note_1771591369178_3", anchor: "the economic collapse, the supply fractures, the quiet starvation", text: "Quiet starvation. The phrase sits in Lianheizhi's account like a stone he swallowed without tasting. Colonies that enter quiet starvation lose penguins to the Walking — not dramatically, not all at once, but in the steady attrition of those who have lost too much and one morning simply face the ice and go. The Promenade Ward's population records for the quarter following this festival are in the archive. I have not counted the discrepancies. I suspect I will not be asked to.", type: :commentary, display: :full
  annotation "note_1771591369178_4", anchor: "the ice was already speaking, and nobody at trading-floor level was important enough to hear", text: "Ice-memory phenomena of this intensity — active corruption threads, pressure-depth emissions carrying olfactory signatures, the structure itself responding to observation angle — are typically documented during the Long Dark, when the boundary between living world and deep memory thins. That ☽'velumae perceived them in full aurora suggests the corruption beneath the Ward had weakened the veil locally, independent of season. Breach-points do this. Fourteen radiating threads from a sealed artifact of deep-magic would do this efficiently.", type: :commentary, display: :full
  annotation "note_1771591369178_5", anchor: "He placed his testimony on top of it, straightened both documents until their edges aligned, and went to the window", text: "The fire-core inventory beneath the testimony. Unbroken seal. He knows what it contains — everyone at his clearance level knows what a quarterly inventory looks like when the reserves are already ash. He placed his clean, formal, aurora-was-clear account on top of the number that would contradict everything he filed, aligned the edges, and chose the window. I have read a thousand civic documents from collapsing administrations. This is the most precisely rendered act of denial in the archive. How remarkable that he wrote it down.", type: :commentary, display: :full
  annotation "note_1771591369178_6", anchor: "a civic recorder reviews his own observations, not the peripheral impressions of soldiers and foreign traders", text: "Peripheral. A Nightshelf trader counting corruption threads from below. A reconstruction veteran reading a blade-grip at twelve paces. Peripheral.", type: :skepticism, display: :popout
  image "img_chronicle_1770546814545_i5p4n3_1772879452689", role: :cover, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1770546814545_i5p4n3_1772879452689"
  image "img_thaw-frost-scarred_1772881360643", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_thaw-frost-scarred_1772881360643", anchor: "The Promenade Ward at peak festival is a thing", anchor_index: 569, caption: "Tide Custom at the Promenade Ward: aurora burning clear, the spires drinking light to violet and white.", size: :large, reference_id: "imgref_1772835792410_0"
  image "img_thaw-frost-scarred_1772881368009", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_thaw-frost-scarred_1772881368009", anchor: "She pulled. The sheath held. She pulled again.", anchor_index: 9733, caption: "The moment the blade would not come free: Aishouwa's frozen grip on a hilt locked by corruption rising from below.", size: :large, reference_id: "imgref_1772835792410_1"
  image "img_thaw-frost-scarred_1772881375348", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_thaw-frost-scarred_1772881375348", anchor: "Dark threads in the ice. Fourteen. Radiating.", anchor_index: 9003, caption: "The corruption beneath: the Fawned Crypt-seal half-buried in sick ice, its pressure-threads spreading outward in geometric warning.", size: :medium, reference_id: "imgref_1772835792410_2"
  image "img_thaw-frost-scarred_1772881392202", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_thaw-frost-scarred_1772881392202", anchor: "He placed his testimony on top of it, straightened both documents", anchor_index: 11451, caption: "The record sealed: what the ledgers do not record, what the spires do not catch, what the blade-watchers cannot see.", size: :medium, reference_id: "imgref_1772835792410_3"
end
