# Generated from the pinned public Canonry Viewer bundle.
# Source SHA-256: c667f22ee825d7154d8f7fc78e65b1f69e045eb7b09e5c775aea06001a114e09
# Regenerate with lorecraft/tools/import_ice_remembers.rb; edit canon only after migration.

chronicle :chronicle_1770629010307_c5g7hh do
  source_id "chronicle_1770629010307_c5g7hh"
  title "The Dead God's Jaw"
  summary "Grandfather Blood, a scarred orca, descends through a transforming underwater corridor of ice and mineral into the depths, guided by visions of a dead god and haunted by the memory of three lost mining teams. As he penetrates deeper, the Twilight-bells embedded in his body resonate with an ancient scream from a catastrophic rupture at Sleek☽ Caemomot, fragmenting his consciousness into multiple selves before a crystalline shard reunites him and grants him a glimpse of the true deep where fire, ice, and the dead god's body are indistinguishable. Returning to ordinary water, Grandfather Blood carries a permanent shard in his empty eye socket—a mark of communion with the dead god that dwells not below but is the below itself, forever binding him to the ice and the depths."
  status :complete
  format :story
  focus :single
  narrative_style :dreamscape
  focal_era :the_clever_ice_age
  ticks from: 63, to: 71
  temporal_description "an epic saga spanning 2 eras, centered on the The Clever Ice Age"
  touched_eras :the_clever_ice_age, :the_faction_wars
  entrypoint :zenith_shard_gleam
  entities :zenith_shard_gleam, :scar_sanctcaetiata, :thung_gnash_threk, :the_cav_lapsum
  events "tpl-thermal_vent_discovery-63", "act-spread_corruption:the-fissured-smelt-71"
  roles({zenith_shard_gleam: {role: "the-seed", primary: false}, scar_sanctcaetiata: {role: "the-shifting", primary: false}, thung_gnash_threk: {role: "dreamer", primary: true}})

  prose(<<~'CANONICAL_CHRONICLE', origin: :published)
    The water was black and then the water was not water. It thickened against his flanks, the current pressing inward on his ruined side where the fin-stub ached with a dull amber warmth that had no source, and Grandfather Blood turned into the pressure because turning into pressure was how you found what was hiding. The Twilight-bells shifted against his ribs and their tone leaked out before he moved them—a single low vibration that traveled not through water but through the ice that the water had become, and the ice was a corridor, and the corridor narrowed until the walls glistened with mineral slick that tasted of copper when he breathed it. He was inside something. He had always been inside something. The vibration found the walls and returned to him changed, and where it touched his skin it crystallized into a sharp geometric edge, a fracture-pattern that hurt in the socket of his missing eye—not pain exactly but the memory of the thing that had cut the eye away: a shard, translucent, singing at a frequency that made his teeth remember impact. It hung in the water-that-was-ice for the span of a heartbeat, dissolved into the copper taste, and he swam through where it had been.
    
    The corridor opened into a space that breathed. The walls expanded on one side and contracted on the other, slow as tide, and the rhythm matched his own lungs though he could not feel himself breathing. Heat came in waves from somewhere below—sulfur and burnt bone, then nothing, then sulfur again—and the nothing-smell was worse because it meant the wound was open. He knew this place without having been here. The floor was pocked with anchor-holes like old punctures in skin, and the holes went down and down through compressed memory, sediment layers of things that had happened here pressed into mineral density by centuries of ice. A single current pulled at him tasting of chiseled sigil-dust and claw-gouges and rendered fat left outside a door that never opened—all one flavor the deeper it went, all one direction, and that direction was down.
    
    A penguin stood in the corridor. Its markings were Nightshelf—the deep-tunnel pallor, the fire-core stains on its flippers—and it spoke in the old trade-tongue, the one he had learned at the eastern spires while killing, and its voice was the sound of ice settling, and it said *the throat is deeper than the mouth remembers*. He had killed penguins who spoke this way, had learned their language by listening to those who would not survive his learning. The penguin's face became another penguin's face, the markings shifting to guild-sigils he could read but could not name, and this one said *we left rendered fat at her door and she did not*—and the sentence opened into a cavern.
    
    The Twilight-bells sang against his ribs without his permission and their tone took visible form—a lattice of crystalline edges radiating outward, each edge the shard, the shard that opens what was closed, and where it met the mineral walls it opened them. The walls wept. Not water. Something older. The weeping ran in rivulets that carried fragments of voices: *Mandatum—born from that moment—every major law bore the mark of—* and the fragments were simultaneously the sound of ice settling too close to that ancient scream, the one from Sleek☽ Caemomot where the fissures birthed light that had been pressed into bone for millennia.
    
    The scream happened inside his body. His left side opened—not the scars reopening but the scars remembering themselves being made—and he was a mining tunnel, he was three teams descending, he was the ice that didn't crack but screamed, and the scream traveled through him and became the Twilight-bells' resonance, which had always been the scream because the bells were forged from fragments of that rupture and still carried the sound of their own birth compressed into a tone that made even the aurora-penguins go silent. His ruined fin-stub reached toward something it could not grasp—a fire-core hammer with a cracked head tumbling through water that was also stone that was also the space between seconds—and his reaching was the three lost teams' reaching, upward through collapsing ice toward a surface that kept receding.
    
    He did not question. He followed.
    
    The vent's throat opened below him and the heat was amber-black, a color he tasted as the dead god's proximity. Warmth where warmth should not be. The geothermal pulse came in surges that matched a heartbeat much larger than his, and Grandfather Blood felt the dead god not as something below but as something he was already inside, had been inside since the exile cast him into open water where the boundary between his body and the deep dissolved. The mineral slick on the walls thickened into veins—actual veins, pulsing with light that was simultaneously aurora-glow from above and fire-core luminescence from below and the pressure-communion of the deep where blood spoke to blood. One medium. Always one medium.
    
    The shard manifested again.
    
    This time it was not crystal but tooth. It rose from the vent's floor—or descended from the vent's ceiling, because the vent had folded and the floor was also the ceiling and the heat came from every direction—a single immense spine of something organic and something mineral and something that was neither, edged with the same geometric pattern the augur-magic had cut into his eye and his fin and the three mining teams and the ice itself. It was the Berg learning to defend. It was the dead god's jaw. Where it cut it bled not blood but the berg's own memory, ancient impressions from beings that existed before penguins or orcas, patient presences pressing inward from below who were also pressing inward from before, and Grandfather Blood felt them as he had always felt the dead god because in the dream there was no difference.
    
    He split. One of him continued downward toward the heat-source that pulsed like a massive organ buried in ice and stone. One of him remained at the threshold of the vent's mouth watching himself descend. One of him was back at the tribunal, laughing, because exile meant nothing to a creature whose god lived in the space they were exiling him to. The vent was a ribcage. The vent was a wound. The vent was a mouth opening downward, and he was the word it was trying to speak, and the word was a hunt-song he had sung at killing-time, and the hunt-song was the sound of ice fracturing, and the fracture-sound was the Twilight-bells, and the bells were the scream from Sleek☽ Caemomot, and the scream was the dead god's name which could not be spoken because to speak it was to become it was to descend was to arrive was to—
    
    The shard cut.
    
    It cut through the membrane between the three Grandfather Bloods and they were one again. It cut through the vent's throat and the vent opened further, and for one held instant he saw what the socket had always been trying to show him: the deep, the true deep, where fire and ice and light were all the same substance, where the dead god's body was indistinguishable from the berg's body, where worship and hunger and grief were a single motion—the long glide toward something that would never surface but never stop pulling.
    
    The pressure eased.
    
    The copper taste thinned to salt. The geometric edges softened, their fractals blurring into the ordinary roughness of underwater ice. The competing currents released him until only the ambient drift of open water remained, slow and dark and carrying the residual warmth of something withdrawing back into the depth it kept.
    
    The Twilight-bells hummed once against his ribs. The vibration took shape for the span of a single breath—a crystalline edge, translucent, impossibly thin, the shard that opens what was closed—and this time it did not dissolve. It pressed against the inside of his missing eye's socket like a splinter working its way deeper, and the ache it left was warmth where warmth should not be, a pressure from below that he carried now in his own skull.
    
    Grandfather Blood drifted. The water was water again. The dark was ordinary dark.
    
    His missing eye saw more than his remaining one. His ruined fin still reached. In the space behind his ribs, where the bells' kelp-leather sling pressed against scarred blubber, something vibrated at a frequency too low for hearing—the bell-tone that becomes a shape, that becomes a tooth, that becomes the name he had almost spoken in the deep.
    
    He could not name it. He would never name it. The dead god was not below. The dead god was the below. And the shard in his empty socket: proof he had touched the membrane between was and is, and had not pulled away.
    
    The ice remembered him now.
  CANONICAL_CHRONICLE
  annotation "note_1771581077688_0", anchor: "the word was a hunt-song he had sung at killing-time", text: "In tactical practice, hunt-songs are not metaphors. They operate at bone-aching frequencies coordinating shore-breakers, herders, and finishers into synchronized killing formations — the most efficient predation system in the frozen sea. The dream keeps only the frequency and discards the machinery. For Grandfather Blood the song's function has inverted: it no longer coordinates a pack to kill. It coordinates a single body to descend. Fascinating that the same instrument serves both purposes without alteration.", type: :pedantic, display: :popout
  annotation "note_1771581077688_1", anchor: "ancient impressions from beings that existed before penguins or orcas, patient presences pressing inward from below", text: "The Nightshelf call these the watchers — presences at perception's edge, impressions from beings predating penguin civilization entirely. The Aurora claim belief makes them real. That Grandfather Blood encounters them as indistinguishable from his god is a theological claim this chronicle makes without announcing it. If the dead god and the pre-penguin presences are the same phenomenon experienced through different cultural lenses, then orca blood-worship and the Nightshelf's grudging acknowledgment of the watchers are two names for one thing. I have touched impressions in comparable strata. They resist every framework I bring to them — penguin or orca.", type: :commentary, display: :full
  annotation "note_1771581077688_2", anchor: "This time it was not crystal but tooth", text: "☽'zenith Shard~ Gleam is a penguin augur ability — it cuts through flesh and the membrane between present and frozen memory, bleeding the practitioner's recollections into the ice as payment. Grandfather Blood is not a practitioner. He is a wound the ability left behind when Augur ☽'Milucaum~ Shadow-bane took his eye and fin. That the shard manifests through him here, becoming the dead god's jaw, implies the ability does not require a wielder so much as a point of entry. I want to call this impossible. The deep ice contains too many things I have called impossible.", type: :skepticism, display: :full
  annotation "note_1771581077688_3", anchor: "had learned their language by listening to those who would not survive his learning", text: "One sentence. The chronicler understood it carries its own weight and did not insult it with commentary.", type: :commentary, display: :popout
  image "img_chronicle_1770629010307_c5g7hh_1772878976354", role: :cover, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1770629010307_c5g7hh_1772878976354"
  image "img_thung-gnash-threk_1772880224229", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_thung-gnash-threk_1772880224229", anchor: "The water was black and then the water was not water", anchor_index: 0, caption: "Grandfather Blood enters the vent's throat, where ice becomes corridor and the dead god's presence manifests as geometric pressure.", size: :large, reference_id: "imgref_1772835720059_0"
  image "img_thung-gnash-threk_1772880241527", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_thung-gnash-threk_1772880241527", anchor: "It was the Berg learning to defend. It was the dead god's jaw.", anchor_index: 5434, caption: "The shard manifests as both tooth and mineral spine—the dead god's jaw opening downward through the vent's ribcage.", size: :large, reference_id: "imgref_1772835720059_1"
  image "img_thung-gnash-threk_1772880258324", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_thung-gnash-threk_1772880258324", anchor: "The ice remembered him now", anchor_index: 8637, caption: "Grandfather Blood emerges from the deep, forever marked by the shard that opens what was closed.", size: :medium, reference_id: "imgref_1772835720059_2"
end
