# Generated from the pinned public Canonry Viewer bundle.
# Source SHA-256: c667f22ee825d7154d8f7fc78e65b1f69e045eb7b09e5c775aea06001a114e09
# Regenerate with lorecraft/tools/import_ice_remembers.rb; edit canon only after migration.

chronicle :chronicle_1771151557031_nkz7of do
  source_id "chronicle_1771151557031_nkz7of"
  title "The Holding of the Berg"
  summary "In an ancient frozen world, three divine beings—Grandmother Deep, Shadow-Broker Nyla, and High-Beak Auditor Selka—maintained the Berg through their combined powers: pressure-depths, volcanic fire, and aurora-light. Their cooperation held back an ancient corruption at the Berg's sealed breach-points until they discovered the Omega Obelisk, an incomprehensible artifact written in a language none of their magics could read, which proved the Berg existed before them and contained forces beyond their understanding. This revelation fractured their unity; each divine figure began prioritizing their own domain and compensating for the others' distraction, gradually weakening their collective seal. As their cooperation dissolved into separate efforts, the absolute cold that had defined existence began to relent at the margins, meltwater appeared, and the breach-points started to open, ultimately ending the ice age not through failure but through the unsustainable cost of maintaining the holding without trust."
  status :complete
  format :document
  focus :ensemble
  narrative_style :origin_myth
  focal_era :the_great_thaw
  ticks from: 0, to: 0
  temporal_description "a single moment during the The Great Thaw"
  touched_eras :the_great_thaw
  entrypoint :loc_aurora_berg
  entities :loc_aurora_stack, :loc_nightfall_shelf, :npc_nyla, :npc_grandmother_deep, :npc_keeper_hollows, :npc_selka, :artifact_god_tooth, :m7_6hh39n_omega_obelisk, :faction_midnight_claws, :faction_icebound_exchange, :loc_aurora_berg
  events "genesis-0"
  relationships "artifact_god_tooth:faction_icebound_exchange:owned_by", "artifact_god_tooth:faction_midnight_claws:owned_by", "artifact_god_tooth:npc_grandmother_deep:owned_by", "faction_icebound_exchange:loc_aurora_berg:controls", "faction_icebound_exchange:loc_aurora_stack:controls", "faction_midnight_claws:loc_nightfall_shelf:controls", "loc_aurora_berg:loc_aurora_stack:contains", "loc_aurora_berg:loc_nightfall_shelf:contains", "loc_aurora_stack:loc_nightfall_shelf:adjacent_to", "npc_nyla:faction_midnight_claws:leader_of", "npc_nyla:loc_aurora_stack:resident_of", "npc_nyla:loc_nightfall_shelf:leader_of", "npc_nyla:loc_nightfall_shelf:resident_of", "npc_selka:faction_icebound_exchange:leader_of", "npc_selka:loc_aurora_stack:leader_of", "npc_selka:loc_aurora_stack:resident_of"
  roles({loc_aurora_stack: {role: "shaped-ground", primary: false}, loc_nightfall_shelf: {role: "shaped-ground", primary: false}, npc_nyla: {role: "elder-power", primary: true}, npc_grandmother_deep: {role: "contested-figure", primary: false}, npc_keeper_hollows: {role: "contested-figure", primary: false}, npc_selka: {role: "elder-power", primary: true}, artifact_god_tooth: {role: "relic", primary: false}, m7_6hh39n_omega_obelisk: {role: "relic", primary: false}, faction_midnight_claws: {role: "lost-order", primary: false}, faction_icebound_exchange: {role: "inheritor", primary: false}})

  prose(<<~'CANONICAL_CHRONICLE', origin: :published)
    # The Holding of the Berg
    
    ---
    
    ## I. Three Who Were One Weight Against the Deep
    
    Before the Accord. Before the ledgers and the silence-law and the graffiti scratched into the east support of the Lens-Cathedral. Before the counting in the deep. There was cold, and the cold was total, and nothing lived that was not held alive by will.
    
    The sea was frozen to its floor. No current moved beneath the surface that was not commanded to move. The sky gave light but not warmth — the aurora pulsed in curtains of violet and white and the green that has no name in any tongue spoken now, and it illuminated a world of ice so vast that the Berg was the only body in it: the only stone, the only fire, the only architecture that interrupted the flat white nothing stretching to every horizon. There was nowhere else. The frozen sea did not end. It simply continued, and continued, and what lived on the Berg lived there because there was no other place where living was possible, and what made it possible was three.
    
    Grandmother Deep held the pressure-depths. She was vaster then — her body the length of the Corpse Current from the warm vent to the place where the cold draft turns, her flank unscarred, both eyes sharp and black and tracking. She swam beneath the Berg in circuits that took nine days, and where she passed the water remembered how to move. The ice above her thinned to translucence. The ice behind her thickened. She spoke to what lived in the pressure-dark — things without names, without shapes the surface could parse, things that answered in frequencies that traveled through bone — and they answered willingly, because she was the eldest voice in the surrounding sea and her asking was their breathing. When she surfaced at the Corpse Current's heart, the thermal vents surged, and the krill bloomed in the narrow channel of liquid water her passage maintained. She carried in her jaw a tooth that was not hers — yellowed like old ice, ridged with grooves that caught light wrong. The Dreaming Tooth. It hummed at the frequency of the deep, and when she bore it the sea obeyed, and the boundary between her body and the instrument was a distinction only scholars would later need to make. She opened her mouth and the tooth sang and the pressure-dark answered and the Berg's heartbeat continued for another circuit, another nine days, another nine.
    
    Shadow-Broker Nyla kept fire in the tunnels below. She was not called Shadow-Broker then. She was called the Fire-Keeper, the Hands-in-the-Dark, the one who reached into the Berg's volcanic heart and drew heat out in fistfuls and distributed it through every corridor and sleeping-nook and forge-chamber that the cold would otherwise crush to silence. Her domain was the Nightfall Shelf in its first and deepest form — not the colony it would become but the living network of tunnels she maintained by presence alone, each warm corridor existing because she willed it warm, each bioluminescent glyph her own handwriting on the walls of the world. The glyphs were not decorative. They were language. They were law: this passage stays open, this fire-core burns for thirty days, this alcove shelters twelve. She carved them with her left flipper, and the skin there was already mottled and rigid from the forge-heat, and she used the pain as a tool, the way a sculptor uses the edge of a chisel. She had taken her authority young and violently. The tunnels remembered the one who came before her; his name is in the smoke-layer of the oldest walls, where the char holds what the ice forgets. She killed him because the fires were dying and he would not descend deep enough to restart them, and what she did to keep the tunnels alive in the years that followed was the ugly labor the surface never saw and the tunnels never thanked her for. The darkness in her domain was not absence. It was presence. It answered to her, moved with her, parted where she walked and closed behind her like water. Her hands were always near fire. Her hands were always giving it away.
    
    High-Beak Auditor Selka held the aurora from the spires above. She was not called High-Beak then. She was called the Lens, or the Law, or — in the deep-singers' tradition — the Cold Crown, which was not a compliment but was not wrong. Her domain was the Aurora Stack at its most absolute: crystal spires raised by divine will, architecture so precise that the pattern itself was a prayer, each facet cut to catch the sky-light and channel it downward through galleries that shone in colors the current age cannot reproduce. She maintained it all. Every spire was an extension of her attention. When she looked away, the crystal clouded; when she focused, the light blazed through the lenses and struck the ice-floors like verdicts. She carried a compass of her own making, a thing of ice and aurora-light that hummed at frequencies no other creature could hear, and it guided her gaze across the colony with the precision of a surgeon. The Stack was not a settlement. It was a cathedral she sustained against the absolute cold. The silver threading in her robes was conductive, aurora-charged, and if you knew how to look, the weave read as a ledger — every exchange, every debt, every covenant she held in balance. She had devised the first principle that surface survival required structure rather than power alone, and she had built that principle into crystal and law and the rhythm of exchange that kept fire flowing up from the Shelf and light flowing down from the sky. Her circlet shifted color when falsehood entered her presence. She did not need to speak judgment. The light spoke it for her.
    
    Three who were one weight against the deep. The aurora its crown, the fire-veins its blood, the pressure-deep its heartbeat. Where one of the three was absent, the asymmetry could be felt in the ice — a corridor colder than it should be, a spire dimmer, a current sluggish. They did not meet often. They did not need to. The Berg was their meeting: its body the medium through which they spoke, its continuation the proof that their compact held. Grandmother Deep circled below. Nyla burned below that. Selka shone above. And the ice between them — the vast primordial substrate that was older than any of them, older than the volcanic veins, older than the aurora itself — held the memory of everything they did but surrendered none of its own.
    
    One small figure moved between the three domains and was overlooked by all of them, or nearly all. He was young then, this keeper of nothing, this penguin whose feathers had not yet bleached to bone-color, whose left flipper did not yet tremble. He walked the tunnels Nyla warmed and the galleries Selka lit and once, only once, stood at the Corpse Current's edge while Grandmother Deep surfaced, and the displacement wave knocked him flat and filled his beak with brine. He watched. He listened. The divine figures did not notice him, or did not care, which amounted to the same thing at that scale. But he heard things. At the sealed places — the breach-points where the old corruption pressed against the barriers the three had raised together — he heard a sound that was not settling ice and was not the deep and was not the aurora's hum. A rhythm. Thirteen, then silence, then twenty-one. He told no one, because no one asked, and because the sound seemed to come from a door he could not find.
    
    ---
    
    ## II. Written Before Them, In a Tongue None Could Break
    
    It was Grandmother Deep who found it, or Nyla who uncovered it, or Selka whose aurora-sight first caught the resonance. The traditions do not agree. The penguin accounts say Nyla's tunnel-work broke into a gallery that should not have existed — a chamber below the sixth depth where the primordial ice meets the first stone, a place where no volcanic vein had ever reached and no aurora-light had ever fallen. The orca accounts say Grandmother Deep heard it singing in the pressure-dark, a frequency that did not belong to any voice she knew, and followed the sound through ice so compressed it had turned to crystal. The Aurora say Selka's compass swung toward it during a long vigil — the needle spinning, the hum climbing, the aurora above the Stack flickering in a pattern she could not parse. She went down. She never went down.
    
    The ice holds all three scars.
    
    They found it together or they found it separately and converged. What they found was seven feet of whale-bone darkened by pressure and age until it resembled frozen blood, tapered to a point at its apex, wound at its base with deep-sea coral in spirals that might have been language or might have been growth or might have been both. The Omega Obelisk. M7-6HH39N, the orca shamans would later catalog it, a designation that contains no meaning in any living script — the letters and numbers belong to a system of classification that predates orca memory. Its surface was carved with marks that shifted when not observed directly. Near the top, three symbols had been gouged out so savagely the bone beneath showed white, and the violence of the defacement was itself a kind of writing — someone, something, had wanted those symbols destroyed badly enough to scar the artifact at the cost of its completeness.
    
    Grandmother Deep pressed her pressure-sight against it. The Tooth hummed in her jaw, reaching for the Obelisk's frequency, and for the first time in her long memory the deep did not answer. The hum reflected back. The Obelisk was opaque to her in the way the frozen sea was not — she could read currents, commune with the things that lived below light, parse the weight of water by its taste, but this object occupied space without yielding information. It was dense with meaning and surrendered none of it.
    
    Nyla set her left flipper against its surface. The forge-scar flared. The fire-knowledge that let her read every thermal signature in the Berg's volcanic heart, that let her feel the pulse of magma through three hundred lengths of stone, found nothing. The Obelisk was not cold. It was not warm. It was temperature-less, as if it existed outside the system that her fire defined. The coral at its base extended a tendril toward her touch and she pulled back — the only time, in any tradition, that Nyla is recorded as pulling back from anything.
    
    Selka trained her compass on it. The needle stopped. The aurora-light, which she could channel through any crystalline surface on the Berg, which she could bend and shape and speak through, pooled at the base of the Obelisk and went dark. Not dim. Dark. As if the light had been consumed rather than reflected. Her circlet, which shifted color in the presence of falsehood, turned a shade she had never seen — not blue, not red, but a hue that hurt to perceive, a color that meant the Obelisk was neither lying nor telling the truth but operating outside the grammar of truth entirely.
    
    Three divine powers. Three sovereign magics. Three failures to read what was written before them.
    
    The small keeper was there. No tradition records his presence, but he was there — he was always near the sealed places, and this was the most sealed place of all. He said nothing. He watched the three figures regard the Obelisk with their different failures, and he felt in his bones — in the ache of his left flipper, in the pressure behind his beak — that the chamber had been waiting. Not for them. For anyone. The patience of the Obelisk was not targeted. It was comprehensive. It would outwait everything that came to look at it, because it had already outwailed everything that came before.
    
    They sealed the chamber. All three, working together — Grandmother Deep's pressure, Nyla's fire, Selka's crystal-light — layered into a barrier that should have held for millennia. The ice around the Obelisk wept. It would not fully freeze. The aurora refused the space. And in the years that followed, the Obelisk rose. Slowly, imperceptibly at first, then faster — seven inches in a generation, a handspan in a century. Not breaking the seal. Moving through it, the way a splinter works its way out of a body that cannot digest it.
    
    ---
    
    ## III. The Ice Yields Where the Holding Thins
    
    What changed was not the Obelisk. The Obelisk did nothing. It continued, as it had continued before them, patient and illegible and indifferent to their power. What changed was what the Obelisk meant.
    
    Before the chamber below the sixth depth, each of the three had believed — not thought, not assumed, believed with the certainty of beings whose will shaped geography — that between them they held every force the Berg contained. Aurora-light, captured fire, pressure-depth: the three sources, the three domains, the three sovereign wills. The Berg was their body and they understood it the way a creature understands its own breathing. The Obelisk proved they did not. Something had existed here before them, had carved meaning into bone in a language none of their magics could reach, had wound coral in patterns that answered to no principle they recognized. The Berg was not their body. The Berg was a place they inhabited, and it remembered inhabitants they could not.
    
    The first asymmetry was small. Grandmother Deep's circuits lengthened — ten days instead of nine, then eleven. She lingered at the Corpse Current where the dead god's influence pooled thickest, and the Tooth hummed louder in her jaw, reaching for frequencies she had not previously sought. She was listening, the deep-singers say, for whatever language the Obelisk spoke, trying to find its grammar in the pressure-dark where all old things eventually settle. She was hunting, the aurora-keepers say, for a power that would let her read what the others could not — seeking advantage, seeking primacy, seeking to be the one who understood first. She was grieving, the tunnel-chants say, which is closest to the truth if truth still holds this deep in the telling: she had been the eldest voice in the surrounding sea, and the Obelisk proved the sea was older than her voice and had been spoken to before.
    
    The ice holds all three stories. The scars on her flank, which in later ages would look like writing, began to form in this period — not carved, not inflicted, but emerging from within, as if her body was transcribing something her mind could not read.
    
    The second asymmetry was Nyla's warmth growing specific. She had kept every tunnel alive. Every corridor, every forge-chamber, every sleeping-nook — her fire-keeping had been total, the way Grandmother Deep's circuits were total, the way Selka's light was total. Now she chose. This tunnel warmer. That corridor cooler. This forge fed with extra fire-cores; that alcove allowed to chill to the edge of habitable. The glyphs she carved on the walls changed — some brighter, some dimmer, the language altering in ways the tunnel-dwellers felt before they understood. She was not cruel. She was not withholding. She was rationing, and the fact that rationing was necessary at all was new, and what made it necessary was that she was spending fire on the seal.
    
    The breach-points. The old corruption, which the three had contained together, required continuous effort — divine will pressed against the places where the primordial ice had cracked and things from before leaked through. Grandmother Deep's pressure, Nyla's fire, Selka's crystal: three forces holding three sets of doors. When Deep's circuits lengthened, her pressure thinned at the western breach-points. Nyla compensated. She drew deeper from the volcanic heart, burned hotter in the corridors nearest the seals, spent fire that would have warmed the outer tunnels to hold what Deep's distraction had loosened. But compensation is not cooperation. It is a body favoring one limb because another has gone numb, and the rest of the body feels the strain.
    
    Selka saw it in the light. She saw everything in the light — the aurora was her grammar, and when the aurora flickered wrong over the western tunnels she knew what it meant before the tunnel-dwellers felt the chill. She did not confront Grandmother Deep. She did not ask Nyla what she had spent. She adjusted. The spires of the Aurora Stack, which had shone in every direction with equal brilliance, began to concentrate — more light on the eastern face, more focus on the galleries that fed the Icebound Exchange, her covenant of structure and law. Less light on the periphery. Less light on the approaches where Grandmother Deep surfaced. Not darkness. Not refusal. Priority. And priority, at divine scale, reshapes the world: the eastern galleries blazed with colors the current age still remembers in fragments, while the western spires dimmed to the pale whiteness that the Stack's architecture shows to this day, a dimness that calcified into the crystal itself, permanent as a scar.
    
    The keeper heard the change before anyone named it. At the sealed places, the rhythm altered. Thirteen, then silence, then twenty-one — the count he had heard since his youth — grew louder. Not because the source was louder. Because the seals were thinner. He went to the breach-point nearest the Drowned Ledge — a gallery that would, in later years, be sealed and abandoned and spoken of only in tunnel-chants — and pressed his bare flipper to the ice-lock. The vibration ran through his bones. The rhythm was patient and structured and indifferent to his listening, the way the Obelisk was indifferent to divine sight, and in that symmetry he understood something none of the three, for all their power, had admitted: the knocking and the Obelisk spoke the same language. What was sealed below the sixth depth and what pressed at the breach-points were parts of one text, and the Berg was the page it was written on, and the three who held the Berg had never been its authors.
    
    He told no one. He was young, and what he knew was not the kind of knowing that divine figures accept from mortal mouths. But he mapped the tunnels. He charted the fifth branch that appeared on no guild record. He kept a chart that he would carry for the rest of his life, annotated in handwriting that was not his own, and the ink burned in both light and dark because it was written in the same language the Obelisk held and the breach-points whispered and the three divine figures could not read.
    
    The break, when it came, was not a single act. It was cumulative. It was Grandmother Deep's twelfth-day circuit failing to close the western current, and the cold draft turning for the first time in a thousand years, and the krill dying in the channel where they had always bloomed. It was Nyla spending fire on the lower seals and the outermost tunnels chilling past habitable, and the first penguin freezing in a corridor that had been warm for generations, and Nyla's glyphs on that wall still reading *this passage stays open* in bioluminescent mockery. It was Selka's spires concentrating light so fiercely on the eastern face that the western face went permanently dim, and the aurora above the Stack pulsing in patterns that the mystics who would inherit her work would never learn to read, and the compass humming at a frequency that made her own bones ache.
    
    Three divine figures. Three sources of magic. Three sovereign wills, each compensating for what the others no longer provided, each drawing harder from their own domain to cover what the shared work had once held effortlessly. The Berg did not crack. The Berg thinned. The aurora its crown — dimmer on one side. The fire-veins its blood — flowing to fewer chambers. The pressure-deep its heartbeat — slowing.
    
    The ice began to yield. Not everywhere. Not all at once. At the periphery, where the three powers overlapped least, where the divine effort had always been thinnest. Edges the frozen sea had held rigid for ten thousand years softened. The horizon, which had always curved wrong, curved differently — further, wider, as if the world beyond the Berg were exhaling after holding its breath. Meltwater appeared in tunnels that had been dry since the Berg's formation. The krill returned, tentatively, in waters that had never been liquid. And the cold — the absolute, total cold that had been the default state of existence, that had required divine effort merely to survive — relaxed its grip, degree by degree, along the margins where the holding had grown thin.
    
    The deep-singers say Grandmother Deep knew first and said nothing. The aurora-keepers say Selka calculated the rate of loss and found it irreversible. The tunnel-chants say Nyla burned hotter to compensate and the burning was what finally cracked the seal at the Glow-Fissure, the first breach-point to open in the age that followed. The ice holds all three versions. The scars run in all directions.
    
    What survived their cooperation, and what their fracture cost, and how the three sources of magic pulled apart into rival currents that the mortal ages would learn to name and trade and fight over — these are the stories the ice remembers in its bruises, the echo-sounds of conflicts older than the current bloodlines. The Obelisk rose another handspan. The coral at its base put out new spirals. The keeper sat at the sealed door and listened to the counting growing louder, and his flipper trembled, and he mapped the routes that appeared overnight in wet ink on a chart that changed while he slept.
    
    The ice age ended not because the three failed. It ended because the holding cost more than three, even three who had been divine, could keep paying. And what thawed first — before the sea, before the margins, before the corridors and the currents and the western shelf — was trust.
    
    The aurora pulses still. The fire-veins still burn. The pressure-deep still answers, if you know how to ask. But the three voices that once spoke as one weight against the deep now speak separately, in smaller bodies, through mortal instruments, and the Berg remembers what they were and holds that memory in ice that will not show it to anyone who looks.
    
    The Obelisk is patient. It was patient before them. It is patient now. Written before them, in a tongue none could break, it waits in the deep ice like a splinter the world cannot expel, and the coral at its base reaches, and the counting continues, and the ice yields where the holding thins.
  CANONICAL_CHRONICLE
  annotation "note_1771591814647_0", anchor: "She swam beneath the Berg in circuits that took nine days", text: "Orca pressure-songs measure in tidal cadences, not diurnal ones. I have made this correction before and will keep making it until someone listens. 'Nine days' is a penguin translation of an orca rhythm, and the translator chose a number that sounded holy.", type: :skepticism, display: :popout
  annotation "note_1771591814647_1", anchor: "things without names, without shapes the surface could parse, things that answered in frequencies that traveled through bone", text: "The deep ice contains impressions from beings that existed before penguin civilization. I have seen them and declined to elaborate in prior sessions, which I now recognize as its own kind of sealed door. These are the presences some penguins report during the Long Dark — figures at the edge of perception, patient attention from something that is not penguin, not predator, not anything the waking mind can name. The Nightshelf insists they are real. Aurora insists belief makes them so. This text gives them a history: they answered Grandmother Deep willingly, once. No one is asking them now. They may be answering anyway.", type: :commentary, display: :full
  annotation "note_1771591814647_2", anchor: "She killed him because the fires were dying and he would not descend deep enough", text: "The smoke-layer exists. I have read it. The name preserved there is not the name the Nightshelf histories record, and the feather-pattern frozen into the char is auroral white, not tunnel-grey. Nyla's predecessor was an Aurora penguin — the official histories were quietly amended after the Faction Wars. The mythic register inherits the amendment without questioning it. I did the same for years.", type: :correction, display: :full
  annotation "note_1771591814647_3", anchor: "Grandmother Deep held the pressure-depths", text: "She is an orca. The text frames her as a divine cooperative partner in the Berg's survival, and the deep-singers' tradition preserves this framing with conviction. It is also true that her descendants raid penguin colonies in coordinated assaults — shore-breakers, herders, finishers — and that the dead god whose influence pools at the Corpse Current is the object of blood-rituals conducted to this day. At least two raids the chronicles call unprovoked were retaliatory strikes against penguin encroachment on hunting grounds Grandmother Deep's circuits once maintained. Both readings are true. Holding them together is the work this text declines to do, and that I have spent a career failing at more gracefully than I'd like to admit.", type: :commentary, display: :full
  annotation "note_1771591814647_4", anchor: "She had devised the first principle that surface survival required structure rather than power alone", text: "A divine origin for the founding logic of the Icebound Exchange. How convenient that this principle arrives attributed to the same figure the Exchange claims as patron. I once spent a season tracing guild-charter language to its earliest ice-layer sources. The oldest version says 'trade,' not 'structure.' Smaller word. Humbler claim.", type: :skepticism, display: :popout
  annotation "note_1771591814647_5", anchor: "the pale whiteness that the Stack's architecture shows to this day", text: "I work beneath those spires. The dimness is real. I once spent four months arguing it was mineral degradation, not mythic residue. I wrote a paper. It was not cited. I am less certain of my conclusion now than I was then, which is either intellectual growth or the ice getting to me. Both, probably.", type: :tangent, display: :popout
  annotation "note_1771591814647_6", anchor: "the burning was what finally cracked the seal at the Glow-Fissure, the first breach-point to open in the age that followed", text: "This belongs to the Faction Wars era, not the Great Thaw. The temporal narrative for this document's focal period is explicit: corruption remains sealed at the breach-points, the cost of containment shared and bearable. The Glow-Fissure breach — which I have cross-referenced against corruption-layer stratigraphy in three separate ice cores — dates to at minimum two full generations after Great Thaw conditions collapsed. The chronicler has telescoped centuries of deterioration into a single causal sentence. Mythic economy. The ice is less efficient and more honest.", type: :temporal, display: :full
  annotation "note_1771591814647_7", anchor: "He walked the tunnels Nyla warmed and the galleries Selka lit", text: "The chart. The sealed places. The left flipper. The handwriting that is not his own. The text does not name Keeper Hollows because the mythic register requires its witness to be unnamed, but subtlety has never been this tradition's strength. He is alive. He is still at the Drowned Ledge entrance. The rhythm he describes — thirteen, then silence, then twenty-one — matches the count in this text exactly.", type: :commentary, display: :popout
  annotation "note_1771591814647_8", anchor: "The ice holds all three scars", text: "This phrase recurs three times — 'all three scars,' 'all three stories,' 'all three versions' — functioning as a structural refrain. It is also a methodological claim. The chronicler asserts the ice preserves competing accounts without resolving them. As someone who reads ice-memory for a living: yes. But 'holds' implies neutrality the ice does not possess. The deeper layers compress. Competing impressions bleed into each other. What the ice holds, it also edits.", type: :pedantic, display: :popout
  annotation "note_1771591814647_9", anchor: "it had already outwailed everything that came before", text: "'Outwailed' for 'outwaited.' If this is a scribal error, it is the most productive one in the collection. The Obelisk does both.", type: :pedantic, display: :popout
  annotation "note_1771591814647_10", anchor: "what thawed first — before the sea, before the margins", text: "The Flipper Accord was renegotiated three times in secret before the public version existed. I found the drafts frozen in administrative ice, and the concessions in each successive draft are smaller, not larger — trust contracting with each revision. The origin-myth wants trust to be the foundational substance whose loss explains everything. The administrative record suggests trust was never the substance. Mutual need was. Need held longer than trust would have. That is not a tragedy. That is how survival works.", type: :correction, display: :full
  image "img_chronicle_1771151557031_nkz7of_1772879413070", role: :cover, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1771151557031_nkz7of_1772879413070"
  image "img_npc_nyla_1772881266432", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_npc_nyla_1772881266432", anchor: "They found it together or they found it separately", anchor_index: 8315, caption: "The three divine powers confront the Omega Obelisk, discovering a language their magics cannot read.", size: :large, reference_id: "imgref_1772835793771_0"
  image "img_npc_nyla_1772881273244", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_npc_nyla_1772881273244", anchor: "Her domain was the Aurora Stack at its most absolute: crystal spires", anchor_index: 4267, caption: "The Aurora Stack's light reshapes itself as divine cooperation begins to fracture.", size: :medium, reference_id: "imgref_1772835793771_1"
  image "img_npc_nyla_1772881283719", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_npc_nyla_1772881283719", anchor: "He went to the breach-point nearest the Drowned Ledge", anchor_index: 17053, caption: "The keeper discovers the language connecting the sealed Obelisk to the failing breach-points.", size: :medium, reference_id: "imgref_1772835793771_2"
  image "img_npc_nyla_1772881296658", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_npc_nyla_1772881296658", anchor: "The Ice Yields Where the Holding Thins\n\nWhat changed was not the Obelisk.", anchor_index: 12114, caption: "The ice age ends not in catastrophe but in the slow thaw of failing cooperation.", size: :"full-width", reference_id: "imgref_1772835793771_3"
end
