# Generated from the pinned public Canonry Viewer bundle.
# Source SHA-256: c667f22ee825d7154d8f7fc78e65b1f69e045eb7b09e5c775aea06001a114e09
# Regenerate with lorecraft/tools/import_ice_remembers.rb; edit canon only after migration.

chronicle :chronicle_1769576268420_9onqiw do
  source_id "chronicle_1769576268420_9onqiw"
  title "The Drift of Broken Things"
  summary "Rend Kzulrora, a scarred orca, drifts beneath the Berg while teaching his young pod member Kzul-kzaith the hunting patterns of their people, including techniques inherited from the fallen Coldbringer Gnash Krukwark. The narrative explores the tension between orcas and penguins living in the Berg's tunnels, where a law of silence (Foedus∴silenti) now governs the penguin civilization following years of orca raids. Rend carries the weight of past conflicts—marked by penguin beaks on a cord and mysterious artifacts he refuses to use—while sensing a deeper wrongness settling over the Berg as both civilizations withdraw inward, their mutual scars becoming structural to their coexistence."
  status :complete
  format :story
  focus :single
  narrative_style :slice_of_life
  focal_era :the_frozen_peace
  ticks from: 191, to: 229
  temporal_description "an extended arc during the The Frozen Peace (38 ticks)"
  touched_eras :the_frozen_peace
  entrypoint :zund_gnash_gnark
  entities :zund_gnash_gnark, :rend_kzul_orca_marauders, :foedus_silenti
  events "sys-reflected_glory:zund-gnash-gnark-202", "sys-prominence_evolution:rend-kzul-orca-marauders-203", "sys-prominence_evolution:zund-gnash-gnark-203", "act-kill_orca:augur-milucaum-shadow-bane-206", "sys-prominence_evolution:rend-kzul-orca-marauders-214", "sys-prominence_evolution:rend-kzul-orca-marauders-210", "act-steal_artifact:rend-kzul-orca-marauders-213", "tpl-crisis_legislation-220", "sys-prominence_evolution:foedus-silenti-220", "act-tradition_commemorates_event:foedus-silenti-221", "act-tradition_commemorates_event:foedus-silenti-222", "act-tradition_commemorates_event:foedus-silenti-224", "act-tradition_commemorates_event:foedus-silenti-226", "act-tradition_commemorates_event:foedus-silenti-229"
  relationships "zund-gnash-gnark:rend-kzul-orca-marauders:allied_with", "rend-kzul-orca-marauders:foedus-silenti:related_to"
  roles({zund_gnash_gnark: {role: "focal-point", primary: false}, rend_kzul_orca_marauders: {role: "passing-through", primary: false}, foedus_silenti: {role: "the-moment", primary: false}})

  prose(<<~'CANONICAL_CHRONICLE', origin: :published)
    The scar wept salt into salt. It always did, mornings — if you could call them mornings, here where the light never fully committed. Rend Kzulrora hung motionless at six fathoms, his right flank tilted toward the Berg's underside, and let the cold work through the kelp-twist tissue where the wound had healed wrong. Healed was generous. Closed. The wound had closed, the way a mouth closes around something it can't swallow.
    
    He breathed when his body told him to breathe. Rose without thinking about rising. The surface broke across his blowhole and the air tasted of old ice and ozone — the aurora was weak today, a pale thread stitching nothing to nothing along the horizon. He sank again. The water accepted him the way it always did: completely, without comment, pressing evenly against every part of him except the scar, where pressure registered as a low specific ache like a sound only his flank could hear.
    
    Below, the Berg's underside stretched vast and dark. He mapped it without trying. Echolocation was not a thing he did; it was a thing he was. The clicks went out from his jaw and came back wearing the shape of the world: the ridge at forty fathoms where ice had calved and refrozen into a jagged lip, the channel beyond it where prey sometimes sheltered, the deeper hollows past that where the Berg's body became something stranger — warmer, groanier, alive with sounds that traveled through bone. He knew every contour the way his tongue knew his own teeth. The younger ones thought he was reading the ice. He was just being still loudly enough to listen.
    
    Kzul-kzaith drifted twenty lengths behind him, doing what the young did in the shallows: rehearsing. The calf — not a calf anymore, not really, but the pod still called her that — was running shore-breaker patterns around the stone marker, a chunk of volcanic rock someone had dragged up from the Nightshelf tunnels generations ago, back when orcas took what they wanted from the Berg and the penguins couldn't stop them. Now it sat in four tail-lengths of water, covered in algae nothing ate. Good for teaching. Kzul-kzaith's body surged and checked in the rhythms Rend had taught her, her dorsal fin riding too high, breaking the surface in little ridges of white water that would announce her to any penguin with eyes. She didn't know the patterns had a name. She didn't know they'd come from someone specific. She swam the Gnash-line without the Gnash, the way water fills a trench after the thing that carved it is gone.
    
    He listened to her move. The particular displacement of a body that hadn't learned economy yet — too much fluke, not enough core. She'd figure it out or the ice would figure it out for her. He didn't correct. Correction was for hunts. Here, in the still water, the body taught itself if you let it. Teaching was watching someone else's body solve problems. Grandfather Blood had taught him that, in the old waters before the Frozen Peace turned raiding into remembrance. You witness the learning the same way you witness the kill — present, attentive, without judgment.
    
    The penguin beaks clicked against his kelp-cord when he adjusted his drift. Twelve of them. Not trophies — debts. Three he'd taken from Coldbringer Gnash Krukwark after the Augur's fire-hammer, because his packmate couldn't carry them anymore and someone had to count. The rest were his own: kills that cost more than they gained, raids that came back smaller than they left. He hadn't added a new beak in two winters. The cord was starting to fray. The Thrumed~ Shadow-glass sat cold against his right ribs where the harness held it, and beside it the Nighted Lantern, both objects he carried the way a jaw carries a cracked tooth. He'd stolen the Shadow-glass from a Nightshelf Augur who had better uses for it. Never activated the thing. Couldn't bring himself to find out what shadows it would show him. They pressed. He noticed. He left them.
    
    Something had changed on the Berg. Not today — over weeks, maybe longer. The orcas felt it the way they felt thermoclines: not as information but as wrongness. The couriers still moved along the edges, small ink-marked shapes hauling their sealed crates through channels of blue-green light, inviolable and irrelevant. But there were fewer voices carrying from the surface settlements now. The penguin alarm-cry networks had gone quiet in a way that wasn't peace. It was held breath. Rend tasted it in the water — a thinning of scent-traffic, fewer waste-streams from the mining operations, the subtle chemical signature of a civilization pulling its limbs inward.
    
    Above them, somewhere in the Berg's honeycombed depths, the Nightshelf tunnels ran silent. They'd been silent for years now — Foedus∴silenti, the law that replaced speech with smoke-oaths and fire-binding. Rend knew part of it was because of him. Because of the raids that tracked penguins by the sound of their work-songs, by the glow of their fire-cores carried through ice-thin walls. They'd made a law of their silence. The silence was a scar he'd left on them, same as the scars they'd left on him. Neither side talked about which cost more.
    
    Kzul-kzaith surfaced behind him. Her exhale was sharp, effortful — she'd been pushing hard against the marker's circuit. He catalogued it without turning: the particular wet percussion of her blowhole, the turbulence pattern of a body that had been moving fast and stopped. Her dorsal fin had stayed submerged the whole last rotation — better, much better — and she was waiting for him to say something. He let her wait. After a while she dove again and resumed her patterns, and the silence between them was its own instruction.
    
    The dead god drifted somewhere out there, past the shelf, past the deep water, past the place where echolocation returned nothing. Rend did not pray. Prayer was a word penguins might use. What he did was simpler: he held the fact of the god's body in the same place he held the fact of his own — sunken, patient, not finished. The blood-rituals were maintenance. You opened the skin, you let what was inside meet the water, you waited. The way you breathed. The way the scar wept salt into salt every morning without being asked.
    
    He thought of the name and then did not think of it. The way you flinch from a hot vent and the flinch is faster than knowing.
    
    Coldbringer Gnash Krukwark
    
    It moved through him like a low-frequency pulse, the kind that traveled through jaw and spine before the brain caught up. Gnash, who had favored his right side after ☽'Netemia's crystal-lance opened his flank — couldn't circle clockwise anymore without the muscle cramping, so he'd learned counter-spin, made the damage work, turned his split dorsal into the current at the end and compensated until compensating became style. Until the fire-hammer. Until after. The pod carried his name the way the water carried heat: distributed, invisible, everywhere. Kzul-kzaith swam his hunt-patterns. Three others in deeper water ran his timing sequences without knowing they were his. The counter-spin, the angled drift against a crosscurrent with a bad fin — that had become technique now. It had become tradition.
    
    No one said the name. The name said itself, in the shapes their bodies made.
    
    Rend Kzulrora sank to twelve fathoms and let the pressure change work against the ache in his flank. Here the Berg's groaning was louder, transmitted through the water column as a vibration he felt in his jaw, his ribs, the base of his skull. He hung there and listened to the ice think its slow thoughts. Above him, Kzul-kzaith was refining her surge around the volcanic marker — better now, less fluke, learning. Below him, the dark went down further than the dead god's patience, which was infinite, which was the only comfort worth having.
    
    A courier crossed the ice shelf above, its shadow passing over the surface like a small cloud. Sealed crate. Ink-marked flippers catching the weak aurora-light. Rend tracked it with the disinterested precision of a body that could kill anything it chose not to. The courier moved on. The shadow passed. The Nightshelf tunnels held their breath above, and the silence that orcas had carved into penguin law pressed down through the ice the same way the Berg's groaning pressed up through the water — two scars leaning against each other, load-bearing now, structural.
    
    The scar wept. The water took what it gave. The beaks on his cord counted debts he'd never finish paying. Kzul-kzaith hit her line clean for the first time — the surge, the check, the angle around the old stone marker — and didn't know what she'd done, and Rend didn't tell her, and the frequency beneath hearing carried it all down into the dark where the Berg remembered everything and said nothing about any of it.
  CANONICAL_CHRONICLE
  annotation "note_1771589621710_0", anchor: "the subtle chemical signature of a civilization pulling its limbs inward", text: "Two penguin civilizations — Aurora Stack on the surface, Nightshelf in the tunnels — rendered from the water as scent, sound, and silence. The chronicler names neither. From below, the distinction between sky-worship and fire-mining collapses into a single question: how much noise does the prey make.", type: :commentary, display: :popout
  annotation "note_1771589621710_1", anchor: "the glow of their fire-cores carried through ice-thin walls", text: "Fire-cores are one of the Berg's three magic sources — alongside aurora-light and pressure-depth. This text touches all three without naming any. The aurora is a pale thread. Fire-cores betray a position. And pressure-depth — blood, force, communion with the deep — is the medium Rend inhabits so completely he cannot see it as power. His blood-rituals, his dead god, the pressure against his scar: all third-source phenomena. I noted in my Foedus∴silenti correction that these ice-thin walls stood inside orca hunting corridors. The fire-cores glowed where they should not have been.", type: :commentary, display: :full
  annotation "note_1771589621710_2", anchor: "back when orcas took what they wanted from the Berg and the penguins couldn't stop them", text: "Deep-ice trade records complicate this. At least two raids from the late pre-Accord period were retaliatory strikes provoked by penguin mining expansion into traditional orca hunting grounds. 'Took what they wanted' is how both sides remember it. Neither side's version accounts for who moved first.", type: :correction, display: :popout
  annotation "note_1771589621710_3", anchor: "Until the fire-hammer. Until after.", text: "Several 'individual heroism' defenses during the Incursion were coordinated Nightshelf operations, never acknowledged. The Augur with the fire-hammer may have been one. It changes nothing about what it cost Gnash.", type: :skepticism, display: :popout
  annotation "note_1771589621710_4", anchor: "kills that cost more than they gained, raids that came back smaller than they left", text: "I have counted the ice-impressions of raids that came back smaller. There are more than either side's official histories record. Every one is a gap in the ice where someone should be — a shape defined by the water that filled it, the way this whole chronicle defines Gnash by the space he left. I am tired of counting absences. The work continues.", type: :tangent, display: :popout
  annotation "note_1771589621710_5", anchor: "the silence that orcas had carved into penguin law", text: "Here is what the Foedus∴silenti entry cannot say: the law was enacted by penguins, enforced by penguins, justified as penguin survival doctrine — and an orca names it as a scar he left on them. Both framings are true simultaneously. I have annotated Foedus∴silenti twice. Neither annotation reached this. Two scars leaning against each other, load-bearing, structural. The chronicler understood something about the Frozen Peace that the diplomatic record never will.", type: :commentary, display: :full
  annotation "note_1771589621710_6", anchor: "he held the fact of the god's body in the same place he held the fact of his own — sunken, patient, not finished", text: "The most precise rendering of orca theology in any chronicle I have annotated. Not prayer. Maintenance. It will not reach the scholars who need it.", type: :commentary, display: :popout
  image "img_chronicle_1769576268420_9onqiw_1772879021974", role: :cover, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1769576268420_9onqiw_1772879021974"
  image "img_zund-gnash-gnark_1772880413586", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_zund-gnash-gnark_1772880413586", anchor: "Rend Kzulrora hung motionless at six fathoms", anchor_index: 133, caption: "The scar wept salt into salt.", size: :large, reference_id: "imgref_1772835691097_0"
  image "img_zund-gnash-gnark_1772880406478", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_zund-gnash-gnark_1772880406478", anchor: "Kzul-kzaith drifted twenty lengths behind him, doing what the young did", anchor_index: 1576, size: :medium, reference_id: "imgref_1772835691097_1"
  image "img_zund-gnash-gnark_1772880464355", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_zund-gnash-gnark_1772880464355", anchor: "The penguin beaks clicked against his kelp-cord", anchor_index: 3074, size: :small, reference_id: "imgref_1772835691097_2"
  image "img_zund-gnash-gnark_1772880442948", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_zund-gnash-gnark_1772880442948", anchor: "A courier crossed the ice shelf above, its shadow passing", anchor_index: 7787, caption: "Two scars leaning against each other, load-bearing now, structural.", size: :medium, reference_id: "imgref_1772835691097_3"
end
