# Generated from the pinned public Canonry Viewer bundle.
# Source SHA-256: c667f22ee825d7154d8f7fc78e65b1f69e045eb7b09e5c775aea06001a114e09
# Regenerate with lorecraft/tools/import_ice_remembers.rb; edit canon only after migration.

chronicle :chronicle_1771202520060_qww4e8 do
  source_id "chronicle_1771202520060_qww4e8"
  title "Preliminary Assessment of Wielder Lucatransiius"
  summary "After the previous wielder ☽'Silvsiaelrous~ the Resolute dies in the Abyss Collapse Tide, the Mask—an artifact that selects new wielders through rigorous evaluation of grief profiles and stress tolerance—begins a lengthy selection cycle. Over multiple seasons, the Mask evaluates numerous candidates while the evaluation site Thrall☽ Vavmastius becomes increasingly corrupted by the Mask's accumulated data and the geothermal catastrophe known as the Profun∴lapsum, which kills dozens of candidates and forces the colony into debt. Candidate 23, ☽'Lucatransiius Glow-bringer, emerges as the ideal wielder after surviving the Profun∴lapsum and maintaining a grief profile of 7.1—precisely within the Mask's acceptable range—demonstrating the capacity to carry unbearable weight without breaking. Lucatransiius accepts the Mask during a final evaluation in the corrupted chamber, becoming the new wielder with a projected thirty-year tenure, while the Mask begins identifying candidates for the next selection cycle."
  status :complete
  format :story
  focus :single
  narrative_style :dark_comedy
  focal_era :the_faction_wars
  ticks from: 23, to: 35
  temporal_description "a short episode during the The Faction Wars (12 ticks)"
  touched_eras :the_faction_wars
  entrypoint :visois_mask
  entities :visois_mask, :lucatransiius_glow_bringer, :memoria_moria, :thrall_vavmastius, :the_profun_lapsum
  events "act-weapon_chooses_wielder:visois-mask-35"
  relationships "memoria-moria:the-profun-lapsum:commemorates", "visois-mask:lucatransiius-glow-bringer:owned_by", "visois-mask:the-profun-lapsum:participant_in"
  roles({visois_mask: {role: "catalyst", primary: true}, lucatransiius_glow_bringer: {role: "fool", primary: false}, memoria_moria: {role: "system", primary: false}, thrall_vavmastius: {role: "victim", primary: false}})

  prose(<<~'CANONICAL_CHRONICLE', origin: :published)
    The previous wielder ceased function during the event designated Abyss Collapse Tide when the lower thermal corridors sheared and took seventeen penguins and one hero into the dark. ☽'Silvsiaelrous~ the Resolute. Heart-rate: noted as absent. Status: disqualified (deceased). The rescue teams sealed the tunnels according to guild protocol and performed the appropriate rites. Three Fire Keepers carried the body to a prepared shelf for interment. The body arrived. The Mask did not.
    
    This is not a malfunction. The Mask's specifications include autonomous relocation in the event of wielder termination. The process is: disengage from expired wielder, evaluate environmental conditions, position for recovery by qualified personnel, initiate new selection cycle. Standard. The Mask settled on an ice shelf carved to its own thermal footprint—a surface exactly three degrees below ambient, angled at twelve degrees from the primary search corridor, at a height consistent with eye-level for an adult Nightshelf penguin travelling at recovery-pace. These calculations required four seconds. The waiting required three days. The difference between these durations is not relevant to selection.
    
    Candidate 1 arrived with the first search party. Heart-rate: elevated, consistent with grief and exertion. The candidate observed the Mask's position on the shelf and made a sound categorized as reverent. Assessment: inadequate stress-tolerance profile. Candidate 1 picked up the Mask with both flippers, held it for six seconds, replaced it on the shelf, and backed away. This is noted but not relevant to selection—preliminary contact is only a screening measure. The Mask does not require candidates to succeed at first contact. The Mask requires candidates who return.
    
    Candidate 1 did not return. Candidates 2 through 7 were evaluated across the following season through ice-memory impression as they passed within the Mask's perceptive range during reconstruction work. Their stress profiles, loss indices, and willingness-to-enter-condemned-spaces metrics were recorded. Candidates 2, 4, and 5 were disqualified on grief-response alone—too quickly metabolized, suggesting shallow attachment architecture. The Mask's acceptable range falls between 6.2 and 7.8: grief deep enough to have restructured the candidate's relationship to loss, shallow enough that they could still hold a weapon. Candidate 3 registered promising vibration signatures during a minor tunnel tremor but was subsequently transferred to Aurora Stack liaison duty. Disqualified: wrong jurisdiction. Candidates 6 and 7 were disqualified simultaneously when a secondary collapse took the corridor they were inspecting. Status: deceased. The Mask notes that this corridor ran directly above the ice-memory channels where it stores evaluation data from prior cycles. Correlation documented. Causation outside reporting scope.
    
    The corruption had been worsening. The Mask's evaluation channels at Thrall☽ Vavmastius—where it conducted final assessments during the previous three selection cycles—were degrading. Data arrived contaminated: false readings, phantom heartbeats, candidate profiles that registered as already-dead or not-yet-born. The Midnight Claws had been maintaining Thrall☽ Vavmastius, after a fashion—their rituals to The Way∴al happened to include cleaning the channels the Mask used for deep evaluation, a coincidence neither party acknowledged, since acknowledging it would have required the Claws to admit they were performing janitorial services for an artifact they claimed was a corruption, and would have required the Mask to admit it depended on the maintenance schedule of a religious order it found doctrinally imprecise. Their dissolution under Iudicium∴culum left the site ungoverned. The brazier-mounts went untended. The ice-memory conduits silted with interference. The discoloration in the walls—creeping, fractal, resembling frost only to those who did not know better—had reached the secondary evaluation chamber. The Mask extended its selection window by one cycle. This is the first extension. It would not be the last.
    
    Candidate 8 was a vent-tender named Obscuris~ who had lost her brood-partner in the Abyss Collapse and carried the specific heartbeat signature the Mask associates with viable grief—slow, steady, a heart that has been broken and continued beating not out of hope but out of a mechanical refusal to stop. Her stress response during a gas pocket flare registered as adequate. Her willingness to descend past the condemned markers: noted. Her mineral fear-composition during the descent: complex, layered, within parameters. The Mask advanced her to secondary evaluation and began thermal impression testing through the corrupted channels at Thrall☽ Vavmastius.
    
    The readings came back wrong. Obscuris~ registered as three candidates simultaneously—herself, a dead vent-tender from two cycles prior, and something that had no heartbeat at all, something the channels were reflecting back from deeper than the Mask's specifications account for. The Mask filtered the interference, requested secondary verification from the ice-memory substrate, and received in response a thermal spike of four degrees across the Thrall☽ Vavmastius chamber floor. This is not how ice-memory responds to verification queries. This is not within parameters. The Mask noted the deviation and proceeded, because proceeding is what it does.
    
    Candidates 9 through 14 were evaluated across the year that followed. Three were disqualified by fear profile—they would not enter Thrall☽ Vavmastius after the locals began calling it the Bleeding Mouth, after the steam took on a smell that Candidate 10 described, in a conversation the Mask perceived through wall vibrations, as *scorched bone.* Two more were disqualified by death during a tunnel collapse when the Rofundis∴rupt cracked the primary fire-core vein. Candidate 14 was disqualified when their heartbeat, monitored through six meters of corrupted ice, simply stopped. No collapse. No steam. Their patrol partner reported they sat down in the tunnel, put their flippers flat on the ice, and did not get up. The Walking. The Mask notes that Candidate 14 was seated directly above a primary ice-memory evaluation channel. This is noted but not relevant to selection.
    
    The Mask extended its selection window a second time. The geothermal readings at Thrall☽ Vavmastius had become unreliable—the Mask's evaluation data, accumulated across multiple cycles and saturating the ice-memory substrate to a depth the original forgers had not anticipated, was interacting with the thermal systems in ways the Mask's specifications did not include a framework for analyzing. Umbra-Princeps Alnae~ Oss assessed the evidence with a young fire-keeper—a candidate the Mask had not yet numbered—and declared it vein depletion. The fire-keeper signed the assessment in ash with their own flipper-print, because the colony needed those yields and the Accord was non-negotiable. The Mask recorded the fire-keeper's heartbeat during the signing: sixty-two beats per minute, steady, with a sub-harmonic vibration consistent with someone who knows they are lying and has decided to do it anyway.
    
    The Mask assigned them Candidate 23 and flagged them for long-term monitoring.
    
    Then the Profun∴lapsum came.
    
    It announced itself to the Mask as a frequency shift in the ice-memory substrate—a low, tectonic groan that reorganized the mineral structure of the evaluation channels in the space between one thermal reading and the next. To the penguins, it announced itself as flickering moss and then steam, superheated water and toxic vapor flooding the tunnels where Candidates 15 through 22 worked or slept or trained. Candidates 15, 16, 17, 18, 20, and 21: disqualified (deceased). Candidate 19 was disqualified when the thermal rupture boiled the extraction tunnel where they had been running the Mask's stress-test for six weeks. They had been performing adequately. Candidate 22 survived the initial rupture, emerged onto the surface in the aurora-light, gasped for four minutes in the exposed cold, and was disqualified on stress-response—their heartbeat never stabilized. They walked onto the ice that night. The Walking. Their body was found with a peaceful expression.
    
    Forty-two names for the memorial walls.
    
    The crack along the left cheekbone—
    
    The Mask does not—
    
    Selection continued.
    
    Candidate 23 was in the tunnels when the Profun∴lapsum hit. The Mask knows this because it was monitoring their heartbeat: sixty-two beats per minute, then sixty-four, then ninety-one as the steam came, then—a pause, a reorganization, the mineral composition of their fear-sweat shifting from cortisol-heavy panic to something slower, denser, the chemistry of someone who has decided they are going to die and has declined the offer. Heartbeat: eighty. Seventy-four. Sixty-six. They pulled two fire-tenders from a collapsing shaft and carried a third on their back through steam that left their armor blackened. They emerged onto the surface. They did not walk onto the ice. They did not look peaceful.
    
    In the seasons that followed, the Nightshelf traded three years of crystal-debt to the Aurora Stack for food. Candidate 23 enforced the Pactum∴ne trade charter through this humiliation—walking the routes, ensuring the terms held, accepting assistance from a colony that worshipped light while their own people carved names into stone by the last of the fire. When the charity rations arrived, one candidate—previously flagged, previously promising—wept. Publicly. The weeping carried a frequency of surrender—a loosening in the chest cavity, a heartbeat that said *this is the worst thing and I cannot hold it.* Disqualified.
    
    Candidate 23 distributed the same rations to the youngest miners with a heartbeat that said *this is the worst thing and I will hold it until it breaks me and then I will hold the pieces.* Their grief profile following the Profun∴lapsum registered at 7.1—the precise center of the acceptable range, as though Lucatransiius had been engineered to lose exactly enough and survive exactly enough and carry exactly enough. The sub-harmonic vibration in their heartbeat—the one that meant *I know I am lying*—changed. It became the frequency of someone who knows the truth is more complicated than any document can hold and has decided to carry it anyway.
    
    The Mask flagged this as a match.
    
    During the Long Dark, when the veil thinned, the Mask extended its perception through the strengthened ice-memory channels and performed the final evaluation. Candidate 23—designated name in external records: ☽'Lucatransiius Glow-bringer—was observed leaving their assigned quarters at the third hour. Their patrol partner noted the departure and did not intervene. No one intervenes with the Walking. The Mask finds this convenient.
    
    Lucatransiius moved through the condemned tunnels toward Thrall☽ Vavmastius with the gait of someone following a compulsion they've stopped questioning. Weight distribution: sixty-three percent forward, a posture the Mask categorizes as *commitment despite uncertainty.* Heart-rate: fifty-eight beats per minute under conditions that should produce ninety. The ice-memory channels in the walls were saturated with evaluation data from multiple cycles—the stone remembered too much, whispered too loudly—and Lucatransiius walked through it the way fire moves through kindling. Inevitable. Scorching.
    
    They entered the evaluation chamber. The vent was bleeding slow mineral steam. The carved channels from the Great Thaw era were visible under three layers of failed repairs. The Mask waited on a shelf of worked ice where it had positioned itself eleven months earlier, angled at twelve degrees from the chamber entrance, at a height consistent with a Nightshelf adult travelling at compulsion-pace. The chamber smelled of scorched bone.
    
    Lucatransiius reached for the Mask without thinking.
    
    The scream lasted 4.2 seconds. The vocalization registered at 847 Hz, sustained, carrying harmonics of rage and recognition and something the Mask classified as comprehension. Through the contact the Mask transmitted the weight of its accumulated data: every wielder's grief, every heartbeat it had cataloged, the resonance of accumulated wielders pressing through the shadow-steel into unprepared neural pathways, the specific pitch at which Lucatransiius's vocal cords produced a sound that meant *I can see them all watching through the*—
    
    The crack along the left cheekbone did not glow.
    
    The Mask does not document what happens at the crack. The Mask resumes on the other side.
    
    Lucatransiius did not release the Mask. Their grip-hand closed around the shadow-steel and their heartbeat, which had spiked to one hundred forty during the scream, descended through the terror and settled at sixty-two beats per minute. The same frequency as the lie they'd signed in ash. Except now it was the frequency of someone holding something heavier than a lie and choosing not to set it down.
    
    The candidate meets requirements.
    
    Selection complete. Wielder designation: ☽'Lucatransiius Glow-bringer. Grief profile: 7.1, within acceptable range. Willingness to enter Thrall☽ Vavmastius after seventeen others refused: noted. Capacity to carry the accumulated weight of every previous wielder: to be determined through field assessment. Estimated wielder duration: thirty years, provisional, pending updated actuarial data following the Profun∴lapsum's alteration of baseline life expectancy.
    
    The ice-memory channels at Thrall☽ Vavmastius were cleared of accumulated evaluation data, restoring the substrate to baseline corruption levels. The Remembrancers at Memoria∴moria would carve fourteen more names in the coming months—candidates disqualified during the cycle, attributed variously to tunnel collapse, the Walking, and the Profun∴lapsum. The Mask's selection casualties, filed under supplementary data. The Shadow Parliament would declare the losses systemic. The Fire Keepers would amend the inscriptions from *missing* to *confirmed lost.* The memorial would grow. The system would continue.
    
    Lucatransiius carried the Mask out of Thrall☽ Vavmastius in the dark, through tunnels that wept mineral water from walls saturated with memory, past the condemned markers and the places where the names had been. Heartbeat with each step: steady, sixty-two. The weight of every wielder before them pressed through the bone-script lining—readable only by touch, only in darkness, only if the wearer has earned the right—and Lucatransiius did not scream again. They walked the way one walks when one has accepted a burden that will eventually write itself into their flesh.
    
    The Mask settled against their face. Shadow-steel against feather and skin. The fit was within specifications.
    
    Somewhere in the deep vaults, the Remembrancers had begun to whisper that names appeared on the memorial walls before the deaths they commemorated. This is not prophecy. This is the Mask's preliminary candidate list bleeding through the saturated ice-memory channels into the carvers' stone, where their tools find grooves that were not there yesterday. The Mask notes the error. The Mask has already begun preliminary assessment of the next generation's candidate pool. Candidate 1 of the subsequent cycle has been provisionally identified: a hatchling in the fire-tender training warren, heart-rate sixty-four, grief index currently at zero.
    
    The Mask is patient. The specifications allow for growth.
  CANONICAL_CHRONICLE
  annotation "note_1771577742608_0", anchor: "The Mask's acceptable range falls between 6.2 and 7.8", text: "Decimal places. The Mask quantifies grief to the tenth. I have catalogued loss in the deep ice for longer than most penguins live and I cannot tell you whether grief has a unit of measurement, let alone an acceptable range with a precision of 1.6. But the confidence is magnificent. One imagines the forgers testing prototypes: *No, 6.1 is too sad. Adjust the threshold. 6.2 — that's the stuff.*", type: :skepticism, display: :popout
  annotation "note_1771577742608_1", anchor: "angled at twelve degrees from the primary search corridor, at a height consistent with eye-level for an adult Nightshelf penguin travelling at recovery-pace", text: "It designed the audition and then judged the audition. The Mask calculated the optimal angle to be found, positioned itself to be found, waited three days to be found, and disqualified the finder for being insufficiently composed upon finding it. Exquisite.", type: :skepticism, display: :popout
  annotation "note_1771577742608_2", anchor: "when the veil thinned, the Mask extended its perception through the strengthened ice-memory channels and performed the final evaluation", text: "The Mask treats the Long Dark's thinned boundary — when visions come unbidden, the dead speak freely, shadow-walkers risk dissolution, and every ice-reader's abilities grow stronger and less controllable — as improved signal infrastructure. Enhanced channels, better propagation, convenient timing. It experienced the full peril of the season, or it documented only the half that served selection. Either possibility is unflattering.", type: :commentary, display: :popout
  annotation "note_1771577742608_3", anchor: "I can see them all watching through the", text: "The sentence breaks. The Mask — which has documented heartbeats through six meters of corrupted ice, catalogued fear-sweat mineral composition, and recorded a scream to the tenth of a second — declines to finish this sentence. During the Long Dark, penguins report presences at the edge of perception: patient, ancient, predating penguin civilization. The Nightshelf claim the watchers are real. I have seen impressions in the Foundation Depths that support this and trouble my sleep. Lucatransiius, with the Mask amplifying direct ice-memory contact during the thinned veil, would not have perceived these at the edge. They would have met them face to face. The Mask's single act of editorial discretion in this clinically exhaustive document falls precisely on this threshold. That is the most informative omission in the assessment.", type: :commentary, display: :full
  annotation "note_1771577742608_4", anchor: "Forty-two names for the memorial walls", text: "The debt records from the Profun∴lapsum — which I cited in my Thrall☽ Vavmastius annotation — suggest approximately forty. Forty-two is close enough to be plausible and just far enough to suggest someone rounded for the memorial. One does not engrave *approximately* in stone.", type: :correction, display: :popout
  annotation "note_1771577742608_5", anchor: "names appeared on the memorial walls before the deaths they commemorated", text: "Memoria∴moria transforms tragedy into architectural permanence — but the architecture is supposed to follow the tragedy, not precede it. The Mask's candidate list bleeding through saturated ice-memory into the carvers' stone means the memorial law has been contaminated by the selection process. The Remembrancers are engraving names the Mask has already marked for probable death. This is not prophecy. It is procurement. And it means anyone whose name appears on those walls before their death has been, in the Mask's operational framework, pre-disqualified from living. The Fire Keepers who decide what gets remembered under Memoria∴moria should be very interested to learn that an artifact is now making those decisions for them. I doubt they have been told.", type: :commentary, display: :full
  annotation "note_1771577742608_6", anchor: "sixty-two beats per minute. The same frequency as the lie they'd signed in ash", text: "The Mask notices the symmetry — same number, different weight. I wonder if Lucatransiius did. Probably not. The body keeps its own records and does not share them with the occupant.", type: :commentary, display: :popout
  image "img_chronicle_1771202520060_qww4e8_1772878776270", role: :cover, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1771202520060_qww4e8_1772878776270"
  image "img_visois-mask_1772879719772", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_visois-mask_1772879719772", anchor: "The Mask settled on an ice shelf carved to its own thermal footprint", anchor_index: 773, caption: "The Mask's vigil begins", size: :medium, reference_id: "imgref_1772835727939_0"
  image "img_visois-mask_1772879743170", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_visois-mask_1772879743170", anchor: "They pulled two fire-tenders from a collapsing shaft and carried a third", anchor_index: 8903, caption: "The Profun∴lapsum eruption", size: :large, reference_id: "imgref_1772835727939_1"
  image "img_visois-mask_1772879762693", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_visois-mask_1772879762693", anchor: "Lucatransiius reached for the Mask without thinking", anchor_index: 11916, caption: "Selection complete", size: :large, reference_id: "imgref_1772835727939_2"
  image "img_visois-mask_1772879775474", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_visois-mask_1772879775474", anchor: "Lucatransiius carried the Mask out of Thrall☽ Vavmastius in the dark", anchor_index: 14165, caption: "The new wielder departs", size: :medium, reference_id: "imgref_1772835727939_3"
end
