# Generated from the pinned public Canonry Viewer bundle.
# Source SHA-256: c667f22ee825d7154d8f7fc78e65b1f69e045eb7b09e5c775aea06001a114e09
# Regenerate with lorecraft/tools/import_ice_remembers.rb; edit canon only after migration.

era_narrative :eranarr_1771754206666_q7m6hx do
  source_id "eranarr_1771754206666_q7m6hx"
  title "The Frozen Peace"
  status :complete
  era :the_frozen_peace
  thesis "The Orca Incursion consumed the cultural differences that had defined each civilization — the secrets, the sacred separations, the legal architectures of managed apartness — and the Frozen Peace discovered that what was spent could not be reconstituted. The peace was real: not performed, not illusory, but maintained by the shared exhaustion of fragments too broken to resume their separateness and too proud to admit they had become something neither culture's language could name. The era's transformation was not from war to peace but from emergency fusion to attempted re-separation — a separation that failed because the hybrid capabilities forged under pressure belonged to no tradition, the bonds formed across cultural boundaries had no clauses in any accord, and the original cultures no longer existed in recognizable form beneath the institutional costumes still worn in their names. Institutions performed authority over things that had already escaped their jurisdiction: artifacts that blessed criminals, orca remnants processed as evidence in tribunals that could not hear them, knowledge persisting in margins no faction could patrol. Meanwhile the corruption the Incursion's boundary-dissolution had released advanced with geological patience through every jurisdictional void — not invading but inheriting, occupying the spaces where separation had once stood and no institution had yet arrived. And because the alternative to the myths was admitting that the cultures being celebrated had been destroyed not by the orca but by their own survival, the era began mythologizing the Incursion with a compulsiveness that looked like reverence and functioned as structural denial. The peace held. Its maintenance consumed more than the war had."
  tone "sardonic"
  source_chronicles :chronicle_1771198067344_lxlcqy, :chronicle_1770882620182_37uu55, :chronicle_1770870650205_79wleb, :chronicle_1770849141294_jqjxq8, :chronicle_1770772658188_i0t928, :chronicle_1770660167130_sjprzp, :chronicle_1770580349229_n25f19, :chronicle_1770546814545_i5p4n3, :chronicle_1769911393082_yn1r8f, :chronicle_1769616578345_ljriln, :chronicle_1769576268420_9onqiw, :chronicle_1769545979344_tjk5fm, :chronicle_1769459190192_4zs4qi, :chronicle_1769451749570_2d76x4, :chronicle_1770581180617_3c4l7o, :chronicle_1770870611592_6e4f46, :chronicle_1770767374880_felzo1

  prose(<<~'CANONICAL_ERA_NARRATIVE', origin: :published)
    The scar from the Grulkzul Omega Strike sang in the deep ice beneath Aurora Stack — a frequency pressed into the crystal lattice in the year 184, still resonating when the last census of the Frozen Peace was taken fifty-three years later. The Foundation Depths carry older impressions, in strata where the blue has turned to black: pressures no living scholar can name, from before any penguin civilization raised a wall on the Berg's surface. The casting's wound was not identical to those ancient marks. But the rhythm rhymed. And the colonies the casting had preserved rebuilt their walls above that resonance, relit their cores, renegotiated their accords in chambers that still smelled of smoke and salt-blood, and called what followed peace.
    
    The Orca Incursion had consumed the separations that defined each culture. The Nightfall Shelf disclosed its tunnel routes and shadow-craft to mount defenses no single tradition could sustain. Aurora Stack deployed sacred barriers alongside practitioners who held no sanctioned right to witness them. The Flipper Accord's garrison clauses became irrelevant when the garrison sectors were overrun, and the boundaries the Accord had codified — sealed tunnels, prohibited crossings, managed distances between peoples who needed each other and feared the needing — dissolved under a pressure that did not care what the clauses said. What survived was neither culture intact but fragments of two civilizations that had purchased their continuation by spending the distinctions that had made them two. The Frozen Peace was the era in which those fragments attempted to become separate again — performing the rituals of separateness, staffing the institutions of separateness, enforcing the protocols of separateness — and discovered, year by year and at compounding cost, that the original cultures no longer existed in the forms their institutions described.
    
    Every chick hatched in those fifty-three years was a victory against oblivion. The festivals that marked each hatching-season carried the weight of the dead in every song, and the songs grew more elaborate as the survivors who could have corrected them grew fewer. Guilds that had competed before the Incursion now cooperated, their combined knowledge preserving techniques that neither possessed alone. The great traditions returned — aurora-blessings, fire-rites, the seasonal krill-counts — and the return looked like restoration.
    
    ---
    
    The Flipper Accord bound Aurora Stack and the Nightfall Shelf in a dependence the Incursion had made absolute. Aurora could not produce fire-core warmth. Its spires rose into polar dark above ice that held no volcanic heat, and every flame that burned in its crystal-walled chambers arrived through Nightshelf hands, extracted from Nightshelf shafts, transported along Nightshelf tunnels through darkness Aurora's citizens could not navigate. The Nightshelf could not survive without surface access, krill-bloom routes, and the aurora-derived crystal stores that powered its deeper infrastructure — could not feed its population without the waters Aurora claimed, could not maintain its light-works without the crystals Aurora mined from ice formations only surface-dwellers could reach. Before the war this exchange was commerce — managed, metered, occasionally withheld as leverage. After the war it was respiration. Neither culture could draw breath without what the other held.
    
    The Accord was renegotiated three times in secret before the public version was signed. The drafts survive frozen in administrative ice — three documents filed in a sequence that tells its own story. Each adjusted terms to reflect leverage that had shifted since the last negotiation. Each produced a framework structurally identical to what it replaced. Aurora's terms had been set when the Stack controlled more surface territory and the Nightshelf's need for krill-bloom access cut deeper than Aurora's need for warmth. By the middle Frozen Peace the balance had inverted. Mining disasters in the deep tunnels — collapses in fire-core extraction shafts, gas events in the lower volcanic passages, equipment failures in corridors that had been cut hastily during the Incursion and never reinforced — turned warmth supply from a question of commerce into a question of colony survival. The Fire Keepers, who controlled volcanic core access within the Nightshelf's own governance, sealed damaged shafts and rationed warmth allocation by guild compliance. Guilds that maintained information containment protocols received full warming-month supply. Guilds that did not found their allocations reduced by increments that looked administrative and felt like suffocation. The Fire Keepers held leverage not only over Aurora's supply but over their own Shadow Parliament — and the Shadow Parliament met in rotating locations, deliberated in coded language, and voted on resolutions that the Fire Keepers had already decided by controlling which delegates arrived warm enough to deliberate.
    
    On the surface, the Pinnacle — the remnant governing body that had claimed custodial authority when the old Council of Luminaries fractured — administered Aurora's zones with the thoroughness of an institution substituting documentation for governance. The twelve aurora-crystals were inventoried each season. No one looked directly at them during the count. This was the peace distilled to a single gesture: objects of immense significance managed through ledger entries that acknowledged their existence without examining their condition. Assessment would require decisions no faction had the authority to make. The crystals were counted. The crystals were not assessed. The inventory was filed.
    
    And below — below the Pinnacle's filed inventories, below the Shadow Parliament's coded deliberations, below the Fire Keepers' sealed shafts — the corruption that the Incursion had released moved through every space the dissolved boundaries had opened. Not invasion. Inheritance. The sealed tunnels had contained it. The prohibited crossings had limited its propagation routes. The managed separations codified in the Accord had been, without anyone understanding them as such, a containment architecture — and the emergency had dismantled that architecture, and the peace had not rebuilt it, because the institutions that might have rebuilt it were too fragmented to coordinate the effort and too proud to admit they shared the problem. Each faction cleansed its own territory. What seeped between territories was no one's mandate. The corruption occupied the gap with the patience of ice forming in a crack. It did not hurry. It did not need to.
    
    In the lower tunnels, in the year 190, a Nightshelf intelligence officer named Cilocum and a logistics coordinator named Otrolal exchanged nine months of correspondence across the Accord boundary — letters that tracked, in the space between formal language and shared grammar, the precise mechanism by which necessities were being reclassified as luxuries by administrators who would never feel the cold. A twelve-crate shortfall in warming-month supply. Not the number itself but the layered reading both correspondents performed: Cilocum hearing what the Stack delegation did not say, Otrolal translating the silence — *someone decided our warming-months are negotiable.* Two trained intelligences arriving at the same conclusion through different channels, one acoustic, one logistical. The crates were never late. They were never sent.
    
    Otrolal's final letter arrived on clean pressed lichen with trimmed edges. The ancestor-bone clasp was absent from the seal. The fire had been tended. The content described the Cell's operations at the sixth vein as *tending a fire that's already gone out.* The care of the document contradicting its message — whatever Otrolal was becoming no longer belonged to a lineage. The phrase migrated into Nightshelf colloquial speech and remained there, applied in time to the Accord itself by those accurate enough to be tolerated. This is how institutions die — not through betrayal but through the quiet reclassification of what is essential by those positioned above its absence.
    
    ---
    
    The orca war-pods had broken against combined defenses and the casting's terrible cost, but the orca had not vanished. Broken pairs drifted at the margins of penguin-claimed waters — warriors bonded by complementary damage, maintaining formations for wars that had ended, performing ceremonies whose audiences had dispersed or died. The Wake-Singers, whose theology had driven the Incursion from territorial raid to civilizational crusade, withdrew from open warfare but descended deeper. They breached the Fissured Smelt and dropped through corruption-scars into routes beneath the Berg that no penguin-built map recorded. They pursued the dead god through passages that punished bodies evolved for open water — tight stone corridors that scraped dorsal ridges raw, pressures that burst blood vessels behind the eye, darkness so total that echolocation returned only the sound of one's own breathing amplified by rock. The penguin colonies could not follow. The penguin colonies could not negotiate about what they could not reach. The threat had moved below the jurisdictional floor.
    
    What remained on the surface was the remnant — orcas in penguin territory with no legal standing the Accord anticipated. Not combatants; the war was over. Not citizens; no framework extended recognition. Not diplomatic entities; no matriarch spoke for the broken pairs, and the Accord's implicit architecture categorized orcas as environmental hazard rather than political actor. They existed in a limbo that could not be resolved without opening the Accord for amendment, and the Accord could not be opened without exposing how little of its framework still described reality.
    
    The tribunal convened in the year 215 to try three orcas, and what it tried instead was its own jurisdictional limit. One defendant would not speak — *Nothing I say means anything here* — a sentence delivered in penguin speech with a precision that shamed the prosecution's formal diction. Not refusal. Observation. The second had learned penguin language while killing penguins, prayed to something sleeping beneath the Berg, wore stolen bells, and watched the judge rather than the prosecution for the entire proceeding. His laugh, when it came, was not bitter. He knew the verdict before she did. The third wore twelve beaks on a cord and answered questions about motive with descriptions of theological obligation the court recorder struggled to transcribe. Nobody counted the twelve beaks against the memorial wall's thirty-seven names. The arithmetic was available. The arithmetic would have raised the question the tribunal existed to avoid: what was the Drowned Ledge? What had the miners breached? What still burned in braziers that should have gone cold years ago? The question was raised once, by a junior clerk with deep-ice clearance, and cut off. Raised again by the defendant and dismissed as theology. The court prosecuted what it could categorize. The rest continued beneath it, unaddressed, worsening each cycle.
    
    By then the legends of the Incursion were already hardening into shapes the ice did not confirm. Aurora's oral tradition celebrated solitary defenders holding colony approaches against massed orca assault — figures of individual courage whose stands had saved their people. The accounts were sincere. They were also partial. At least two raids preserved in the tradition as unprovoked orca aggression were retaliatory strikes provoked by penguin encroachment on established hunting grounds — the provocation trimmed from the oral record, the retaliation preserved as evidence of orca savagery. Several defenders credited with solitary stands had in fact been supported by coordinated Nightshelf intelligence operations: shadow-craft networks routing information and supply through channels that remained classified after the emergency that justified them. The Nightshelf could not claim credit without revealing capabilities it preferred to keep hidden. Aurora could not acknowledge the support without undermining the heroic narrative that legitimized the Pinnacle's authority. The intelligence apparatus itself was quietly re-attributed — a predecessor of the Shadow-Broker who had been an Aurora penguin, not Nightshelf, erased from the record and replaced with a lineage that made the operation appear to have always been a Nightshelf institution. Tidy. Functional. Irreconcilable with the ice.
    
    And the orca testimony — the only account that described the casting as something suffered rather than achieved, the snapping of pod-bonds felt from within — survived solely in transcripts extracted under coercive memorial protocols. The witness's flippers shook throughout. The transcriber noted the tremor. The archive preserved the notation, filed the testimony as evidence, and used it to celebrate the event that had destroyed the witness. The best record of what the penguin defenders actually accomplished existed only in the words of an enemy compelled to describe his own annihilation. The myths required cultures that no longer existed in the forms the myths described. Admitting this would require admitting the peace was built on fictions. The fictions were maintained.
    
    ---
    
    What the Incursion had forced open, the Frozen Peace fought to reseal — and the fight consumed more institutional energy than the original opening had. The Nightshelf proverb carved in fire-core shorthand across guild-hall lintels — *Share only what you must; the rest is warmth you cannot recover* — had meant knowledge-hoarding before the war. During the Frozen Peace it acquired a second resonance, a lament for what had been disclosed under pressure and could not be recaptured. The Way∴ens networks quoted the first clause as the orthodoxy they opposed and sent disciples along trade routes the Fire Keepers could not fully patrol. The Fire Keepers quoted the full proverb and restricted warmth access to guilds that complied with containment protocols. Neither faction possessed the strength to win. Both possessed enough to prevent settlement. The stalemate consumed energy that might otherwise have been directed downward, toward what rose through every jurisdictional gap, which was precisely the corruption's advantage: it required no energy at all.
    
    The Grulkzul Omega Strike was the argument's centerpiece, cited by both sides as conclusive proof. The casting had fused Nightshelf fire-knowledge with orca-derived blood-working — practitioners who did not fully understand what they were building, producing a weapon of civilizational consequence that no council had authorized because no council possessed the knowledge to evaluate it. Hoarded knowledge had made the casting possible. The casting's consequences — the corruption scar, the frequency that would not stop, the physical damage to anyone who handled the altered ice — were the argument for why hoarding produced catastrophe. The sealed-knowledge faction held up the weapon. The shared-knowledge faction held up the wound. Same event. The argument was irresolvable because both readings were correct.
    
    Meanwhile the Nightshelf maintained capabilities the official histories recorded as ended. Deep in the tunnel network, in a corrupted cavern, four miners — unnamed because the record was reconstructed from orca testimony that did not individuate prey — maintained infrastructure for combat techniques the Accord's second renegotiation had formally prohibited. The lead miner's defensive stave-thrust was identified as Nightshelf-trained by an observer who could read the signature. Four lives, one corridor, no names on any memorial. These figures were the Nightshelf's actual architecture: invisible, uncredited, load-bearing. An engineer who caught a teacup before it shattered on a stone floor and held a trembling hand in an audit chamber, never speaking. Coded ledgers kept in hide and ink that outlasted the frozen-stone archive they were meant to supplement. The Nightshelf's redundancy — two walls, two counts, two records of every transaction, the institutional assumption that every primary archive would be compromised — proved to be the only methodology adequate to an era in which the ice itself turned out to be rewritable.
    
    For forty years, corrupted fire-core records had been maintained by a custodian who walked past the sixteen cores she had completed with stolen warmth, counted them, and could not stop counting. She was the system's product, not its aberration. *The orbit requires bodies* — interrupted before the admission could complete, cut off by the auditor who uncovered the falsification and understood what the full sentence would confess: that the warmth-supply chain around which the colony organized its survival required lives fed into it to function. The auditor performed the honest count despite the tremor the corrupted ice gave her — the physical cost of reading altered records, documented at Foundation stratum 4-A. Something in the reader's own thermal signature shifted. Something in recall changed. The corrupted ice did not care who read it. Every shortage projection built on the founding-era baselines was now suspect, and the cascading consequence was not abstract. Penguins would die from allocations calculated on numbers that had never been true. The Pinnacle acknowledged the crisis. The Pinnacle reframed it as individual moral failure. The system continued.
    
    The surviving artifacts, meanwhile, operated outside every framework that claimed them. The Dreaming Tooth controlled Wake-Singer theology — whoever held it held leverage over orca religious motivation and made themselves a target for retrieval. The Crypt-seal sat half-buried in corrupted ice at floor level, unnoticed for weeks, because nobody in the upper galleries examined the floor. And the Aurora-harp, in nominal Pinnacle custody, acted on its own terms entirely.
    
    In the year 224, the harp completed a circuit the Pinnacle had not authorized — with deep ice, with corruption-threaded strata, with something below the Berg that answered. A smuggler — faceless, running supplies to colonies the Accord had abandoned — stood in the activation's path. Fire-core residue and copper and the smell of heated ice. The blood-salt taste going out. The harp blessed a criminal. The criminal blessed it back: fire-core warmth wrapped in stolen cloth, left at the instrument's base for no one. Unsanctioned. Unwitnessed. Reciprocal. No institution claimed the exchange. No protocol described it. The Pinnacle stationed an observer at the angle where faces were visible rather than light — intelligence work dressed in custodial clothing, documenting what could not be governed, writing into the record *we were watching* because watching was the last form of authority available.
    
    From below, during the activation, the ice noted pressure changes. A formation-era spire, older than any Pinnacle protocol, produced a phrase the records office classified as atmospheric notation: *They would name it wrong.* It was not atmospheric notation. Whether the ice passed judgment or remembered passing judgment was a distinction growing thinner with each review. The Foundation Depths contain impressions from before penguin civilization. Some of those impressions move when read. The deep ice has opinions about how its testimony is used. Or it remembers having opinions, and the difference no longer matters.
    
    ---
    
    The jurisdictional voids between factions were not empty. They were the spaces where the era's actual work was done and undone — where individuals improvised what institutions could not authorize, and where the corruption advanced without resistance through corridors claimed by two powers and patrolled by neither.
    
    The Pinnacle, the Threshold, and the remnant E'frostlings shared a colony but not a government. The intelligence networks that a single broker had held in careful tension — guild-masters answering through shadow channels, information flowing along lines only she could see — shattered with her confession, and the guild-masters who had reported to her now competed with each other in the deep tunnels. The competition expressed itself as incidents. The incident reports described the incidents with specificity. The specificity indicted the reports.
    
    In the year 230, the colony's fire-core margin narrowed to a calculation that entered common speech and would not leave: *Forty-seven days from dark.* The number came from a single competent figure who walked the gap between Pinnacle authority and Shadow Coven territory because no one else would — ninety days of crisis management from the original forty-seven, descending into tunnels that eroded him with each passage. He lost count of his descents. He lost the name of a man he had worked beside for two seasons. He retained with perfect clarity the one memory that justified everything — but memory erosion was indiscriminate, and what remained with sharp edges had been reconstructed, ice refreezing around an absence and holding the shape of what was there. The connection to the Walking — a corruption-pattern of compulsive descent documented in the deep layers — went unnamed in his account. The parallel was structural. The chicks survived. Whatever else he became, that figure of ninety days in the dark was real. The Pinnacle built the doors. The Shadow Covens contested the keys. He stepped around the frame.
    
    By the last years, the fracture had become geometry. The economic collapse of 235 arranged the colony into three distances from the floor, three versions of the same reality. Above, on the Promenade, Tide Custom demanded that candidates for guild recognition burn months of fire-core warmth in spectacle displays while two public braziers sat dark on the level below — worthiness performed upward, cost distributed downward, the upper galleries seeing the aurora spectrum while the trading floor saw the underside of silk and the dark spots where warmth had been. An observer at the upper level aligned his papers and did not look down.
    
    At floor level, a Nightshelf observer counted corruption threads in ice that had been sitting in place for weeks — stratum-14 emissions, pre-penguin, the olfactory signature connecting surface rot to deep strata through a fracture the collapse had widened. Something geological using the era's institutional cracks as openings. Something older than any culture on the Berg exhaling through gaps no culture was watching. The Crypt-seal half-buried in that corrupted ice, noticed by a Nightshelf observer because the Nightshelf notices what lives at floor level. Surface-dwellers see spectacle. Tunnel-dwellers see infrastructure. Infrastructure is where the rot shows first.
    
    Between above and below, at blade-level, a soldier received a confiscation order for a sealed artifact radiating deep-magic — received it in front of the Nightshelf delegation, the dropped flipper a gesture whose authorship extended upward past where the soldier stopped looking. The chain of command was named and believed to be understood. The chain of command had parents the soldier could not see from twelve paces. And moving through all three levels, appearing in each account as a different figure — protector, instrument, frightened penguin with a frozen blade and blood already dry on her flippers — was a single body that came from somewhere the records did not trace and that cost someone the records did not name.
    
    The response to a geological threat requires geological patience. The penguin factions operated on political timescales and competed with each other more energetically than they addressed what rose from below. The corruption did not compete. It inherited.
    
    ---
    
    The orca remnant gave the era its last and most honest testimony.
    
    At the Still Pools in the year 237, two orca maintained a two-count formation for which no war remained. One carried a dead flank; the other, a dead ear. They fit together because they were broken in matching geometries — the damaged side of one aligned with the functional side of the other, compensating, completing, holding the shape of a war-pair across years in which no war-pair was needed. The ice beneath the Still Pools carried impressions of at least three other pairs configured identically across the decades of the Frozen Peace. None lasted. The compensatory structure was inherently unstable: it required both to remain precisely as broken as they were when the bond formed. Recovery would destroy the fit. So would further injury. The bond existed in the narrow margin between healing and worsening, and margin was a space the Frozen Peace knew well.
    
    One arranged kills on the ice in geometries — presenting the angle of the strike to an audience that was not there. The compulsion that remains when the context that shaped it has been destroyed. The Foundation conducted census ceremonies for a decade after the colonies being counted had been abandoned; everyone keeps counting. The other took up the counting, maintaining the function the first had released, substituting presence for purpose. *We still work.* Prayer. Confirmation. And then permission — spoken while drifting into the flank position for a final strike, choosing the two-count over refusal, choosing the formation over the silence that would follow its dissolution.
    
    ---
    
    The Frozen Peace held for fifty-three years. The festivals returned and the songs named the dead and the chicks were counted each season as proof against oblivion. Hide and ink outlasted frozen stone — the Nightshelf's paranoid redundancy saving the record when the ice proved rewritable, tending truth in margins no faction thought to patrol. Fire-core warmth wrapped in stolen cloth outlasted the institutions that prohibited the exchange. A smuggler and a harp completed a circuit that no accord had authorized, and the circuit held. An auditor did the honest count despite the tremor the corrupted ice put in her hands. A figure walked the forty-seven days and then the ninety, and the chicks survived. An orca took the flank position and did not turn away.
    
    The ice beneath it all continued to sing — the old frequency from the casting joined by newer harmonics from the corruption threading upward through every crack the era's fractures had provided. The Wake-Singers descended deeper, following the dead god's call through passages the penguin colonies could not reach and could not seal behind them. The artifacts acted on their own authority. The myths hardened. The Accord persisted because the alternative was dying, and the terms satisfied no one, and no one could afford to open the document because the negotiation would reveal that the cultures it described had already been replaced by what those cultures had become in surviving each other.
    
    Somewhere in the administrative ice, three drafts of the same accord lie frozen in sequence — each a failed attempt to write a future that fit the past's institutions. Somewhere in the deep layers, a frequency rhymes with something older than civilization. Somewhere in the Foundation Depths, an archivist whose assistants have been reassigned and whose committee has been dissolved reads the ice and cross-references and annotates, because the count has to be honest, even when the medium it is recorded in is not.
    
    The peace held. The chronicles that follow are what it cost.
  CANONICAL_ERA_NARRATIVE
  image "img___era_narrative___1771762495789", role: :cover, url: "https://theiceremembers.com/raw/project_1765083188592/img___era_narrative___1771762495789"
  image "img_chronicle_1769911393082_yn1r8f_1772879189376", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1769911393082_yn1r8f_1772879189376", anchor: "tribunal convened in the year 215 to try three orcas", anchor_index: 9253, caption: "The tribunal's judgment: exile rather than execution, as the memorial wall of thirty-seven names looms behind the judge.", size: :large, reference_id: "enimgref_1771759560173_0"
  image "img_chronicle_1769616578345_ljriln_1772878976048", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1769616578345_ljriln_1772878976048", anchor: "auditor who uncovered the falsification and understood what the full sentence would confess", anchor_index: 15925, caption: "The weight of buried truth and the cost of survival settle into acceptance and accountability beneath the merciless aurora.", size: :large, reference_id: "enimgref_1771759560173_1"
  image "img_chronicle_1769576268420_9onqiw_1772879021974", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1769576268420_9onqiw_1772879021974", anchor: "two orca maintained a two-count formation for which no war remained", anchor_index: 22742, caption: "Broken pairs drifting at the margins: compensatory structures held in the narrow margin between healing and worsening.", size: :large, reference_id: "enimgref_1771759560173_2"
  image "img_chronicle_1769451749570_2d76x4_1772879272456", role: :inline, url: "https://theiceremembers.com/raw/project_1765083188592/img_chronicle_1769451749570_2d76x4_1772879272456", anchor: "Fire-core warmth wrapped in stolen cloth outlasted the institutions that prohibited the exchange", anchor_index: 24557, caption: "A workbench where aurora-light is channeled through precise compression, the fracture within the fire-core spreading and sealing under careful control.", size: :medium, reference_id: "enimgref_1771759560173_3"
end
